### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by sylvainpaquet** [lucent-sea/Remotely#102]
Hello Jay-Rad

Sorry I had not yet put the message saying that I understood how to return the compiled files
I managed to modify the files in French
But I have to change the download path of the Remotely-Server-linux-x64.zip file because it is on your server
on the other hand I noticed when I compile I miss files including those which must be in the download folder
do you have an idea
cordially

**Comment by sylvainpaquet** [comment]
I understood how to put the files in the download folder now I still have how to understand how to configure the powershell file
if not last question
when there is a next update, I would have to update the news manually because otherwise everything I am going to be overwritten
thanks again

**Comment by lucent-sea** [comment]
Unfortunately, I don't have any plans of supporting multiple languages.
