### ISSUE TITLE
Windows7 support as clients

### ISSUE THREAD

**Issue by ksingh7** [lucent-sea/Remotely#103]
Hi @Jay-Rad 
First of all , thank you for this work your tool works like a charm. You are a genius.

A few questions, would be great if you can answer
1) Can the clients be on windows 7 / 8 ?
2) If yes do you happen to have the exe files for win7/8
3) Do you have instructions how once can build exe file from source for win 10/7/8 ( for Client agent )

**Comment by lucent-sea** [comment]
I don't have any plans for official supporting Windows 7 or 8, especially with 7 being way paste end-of-life.

However, last I tested, the Windows 10 EXE was working on both.  Performance is much worse on Windows 7, though, due to lack of DirectX Desktop Duplication support.
