### ISSUE TITLE
uac support

### ISSUE THREAD

**Issue by siikty** [lucent-sea/Remotely#104]
If the UAC window pops up on the remote computer, there will be no response on the web. Can UAC be supported?

**Comment by fanuelsen** [comment]
I think this is a limit in Windows, as how the application is run when you launch the instant support client. If you install the resident agents it will work with UAC.

**Comment by lucent-sea** [comment]
There's no way of launching a process that has access to the UAC screen unless it's launched from a Windows Service.

**Comment by siikty** [comment]
it work for me ,thank you very much!

**Comment by sinichi19** [comment]
@siikty how its work?

**Comment by siikty** [comment]
> @siikty how its work?
I use psexec to bypass UAC.
First, I use psexec to start the client and make it have system permission. Then when I am remote, I use psexec to enable the new process to bypass UAC. Maybe all the flow is like this, but in fact, I wrote some scripts and exe to automatic operation , and now  it‘s enough for me .You can try to see if psexec is satisfied.
here is the psexec link
https://docs.microsoft.com/zh-cn/sysinternals/downloads/psexec
PsExec64.exe -s -d -i "cmd.exe"
