### ISSUE TITLE
Error on EntityFramework Model

### ISSUE THREAD

**Issue by Nonobis** [lucent-sea/Remotely#106]
Microsoft.EntityFrameworkCore.Model.Validation[10620]
The property 'CommandResults' on entity type 'CommandResult' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
[40m[1m[33mwarn[39m[22m[49m: Microsoft.EntityFrameworkCore.Model.Validation[10620]
The property 'PSCoreResults' on entity type 'CommandResult' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
[40m[1m[33mwarn[39m[22m[49m: Microsoft.EntityFrameworkCore.Model.Validation[10620]
The property 'TargetDeviceIDs' on entity type 'CommandResult' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
[40m[1m[33mwarn[39m[22m[49m: Microsoft.EntityFrameworkCore.Model.Validation[10620]
The property 'Drives' on entity type 'Device' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
Hosting environment: Production
Content root path: /var/www/remotely
Now listening on: http://[::]:5000

**Comment by lucent-sea** [comment]
These don't get compared, so I'm not worried about it right now.
