### ISSUE TITLE
Setting groups and alias at install time

### ISSUE THREAD

**Issue by swilkey** [lucent-sea/Remotely#117]
Hi Jared,

Thanks again for all the great work you've been doing on remotely.  The new chat method is a lovely enhancement over the old one.

I noticed that the installation zip file has changed from being 19Mb to 113Mb.  Is this because you have changed from a framework dependent installation to a self contained one or is it that you are now including the dot net runtime in the installation?

In the documentation on the download page it advises that we can complete some of the device settings from the command line at installation time:

> Remotely_Installer.exe -install -quiet -path Remotely-Win10-x64.zip -organization "My Tech Shop" -organizationid "0b3d706b-9c5d-41e6-8ae9-5720d16324e6" -serverurl "https://remotely.mytechshop.com" -devicegroup "Customer Group 1" -devicealias "Front Desk" -deviceuuid "eebb4d87-5459-4976-989e-a7876dffc69c"

I'm not sure where these parameters are stored on the client, and my initial thought was that they were sent to the server only at installation time, however, if the remotely service doesn't get started after installation, the change is never applied to the server so therefore it must be stored somewhere.  Through testing I found that I can change these details on the server simply by reinstalling the client with the new settings and then running the remotely service again.

The problem is, doing this with the old installer was slow, but now that the installer has to install a much bigger file it takes much longer to do, even if you supply it as a local zip file.  I'm wondering if it is possible for the remotely installer to detect whether it has already installed the current version of remotely and if it has, to simply update the settings for it?  Alternatively, is there somewhere we can edit those settings on the client directly rather than doing a complete reinstall?  I've hunted for registry entries and for text files where you might be storing this but haven't located them.

Thanks again,
Stephen

**Comment by lucent-sea** [comment]
Yes, the deployments are now self-contained.  That means they include the dotnet runtime, so it doesn't need to be installed.  I don't plan on changing this.  There are too many things that can go wrong with trying to install and maintain the .NET Core runtime system-wide.

Those are all the options for initial installation.  The only options that make sense to change post-installation are Device Group and Device Alias, which can be done on the Edit Device page.  The edit button is the right-most on the grid.

Please be advised that I'll be closing GitHub issues that aren't specifically bugs.  For asking general questions, please use the Reddit group: https://www.reddit.com/r/remotely_app/.  For feature requests, please use Feature Upvote: https://remotely.featureupvote.com/
