### ISSUE TITLE
Problems listing devices in GUI when reaching a certian amount of devices.

### ISSUE THREAD

**Issue by fanuelsen** [lucent-sea/Remotely#118]
**Describe the bug**

When 800-1000 devices register with the server the device listing gets unresponsive and unable to operate.

**To Reproduce**

You could probably populate the SQLlite instance with fake devices to test this out. Else you need access to alot of devices.

**Expected behavior**
The GUI should still be able to operate. Without lag or the website becomes unresponsive.

**Desktop (please complete the following information):**
- MacOS / Windows
- Firefox, Chrome, Safari. All the latest versions

**Additional context**
A resolution could be to only list a 100 devices at a time and make a load more button to list more, or to make several pages with devices.

**Comment by lucent-sea** [comment]
This has been on my to-do list for a long while, but I've kept putting it off due to indecisiveness about how to implement it.  Whether to bring in a library or implement myself, add React or keep it vanilla, etc.

This will probably be the next thing I work on.

**Comment by fanuelsen** [comment]
I'm not a developer myself, but if you want me to help out test anything i will gladly help. Thanks for making this great product.

**Comment by lucent-sea** [comment]
Pagination was added in the latest release.

**Comment by lucent-sea** [comment]
Just following up.  Did the client-side pagination help?  I kinda went the easiest route for now since I'm short on time.  I'm going to post some stuff soon to see if there's enough community interest in helping prop me up so I can work on this full-time.

**Comment by fanuelsen** [comment]
Great, thanks! I will try to update Remotely to day and see.

**Comment by fanuelsen** [comment]
It works great :) Thanks for fixing this.
