### ISSUE TITLE
invisible mouse

### ISSUE THREAD

**Issue by sylvainpaquet** [lucent-sea/Remotely#120]
hello jared
I hope you are well
I had sent you some time ago a message that I meet
When I do a telemaintenance with your application I do not see the mouse so I do not know where I am on the remote screen
have you ever had this problem or do you know how to solve it
thank you very much for the effort you are making on your application

**Comment by lucent-sea** [comment]
The mouse isn't captured on the remote end.  It's intentional.

The remote mouse will be wherever your local mouse is hovering over.

Unless you mean when you're on a touch screen.  In which case, it's tap-based.  You tap where you want to click.  It mentions it in the readme.
