### ISSUE TITLE
When trying to log in, I get sent back to the homepage

### ISSUE THREAD

**Issue by stevesobol** [lucent-sea/Remotely#122]
I can't log into my Remotely install.

Server: Ubuntu 18.04.5, 64-bit
I am browsing on Windows 10 Pro with all of the updates.

This problem involves logging into the website - it has nothing to do with remote control (I don't get that far)

Steps to reproduce:
1. Go to my Remotely homepage
1. Click "Login"
1. Enter valid login credentials

Expected result: 
- I get logged in

Actual results:
- On Google Chrome, as well as Brave (a Chromium-powered browser), I get kicked back to the home page and in my Developer Tools, the Issues tab tells me:

```
Mark cross-site cookies as Secure to allow setting them in cross-site contexts

Cookies marked with SameSite=None must also be marked with Secure to allow setting them in a cross-site context. This behavior protects user data from being sent over an insecure connection.

Resolve this issue by updating the attributes of the cookie:

Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.

Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests

1 cookie
Name	                                Domain & Path
.AspNetCore.Identity.Application	steves-cool-remotely-server.com/
```

This happens when I try to log in with Brave or Chrome. Oddly, it does NOT happen with Microsoft Edge (not on my laptop, anyhow), and I'd expect that it WOULD happen, because I'm running the new Edge built on top of Chromium.

It does not happen with the latest Firefox.

(To be clear, I CAN log in with Edge or Firefox, but not Chrome or Brave.)

Thanks for taking a look at this.

**Comment by stevesobol** [comment]
https://www.thinktecture.com/en/identity/samesite/prepare-your-identityserver/

_To be backwards-compatible, the default for same-site cookies did not change the previous behavior. You had to opt-in to that new feature and explicitly set your cookies to SameSite=Lax or SameSite=Strict to make them more secure. This has been implemented in .NET Framework and in all common browsers. Lax means, that cookies will be sent to the server on initial navigations, Strict means that the cookies will only be sent when you already were on that domain (i.e with the second request after initial navigation)._

_Sadly, this new feature was only slowly adopted (only 0.1% of all cookies handled on Chrome world-wide were using the SameSite flag, based on Chrome's telemetry data in March 2019 [Source])._

_Google decided to push adoption of that feature. To enforce that, they decided to change the default in the worlds most-used browser: Chrome 80 will require a newly specified setting SameSite=None to keep the old way of handling cookies, and if your omit the SameSite field like the old spec suggested, it will treat the cookie as set with SameSite=Lax._

_Please note: The setting SameSite=None will only work if the cookie is also marked as Secure and requires a HTTPS connection._
```

Of note: My Remotely server is running on HTTP on port 82, under nginx; I have a haproxy instance in front of it, terminating SSL and proxying connections to nginx. For a second, I thought that might be a problem. But if it was, none of the browsers would work. Two of the four do.

**Comment by stevesobol** [comment]
I can visit brave://flags (or chrome://flags if in Chrome) and turn off the _SameSite by default cookies_ setting and then I'm able to log in.

**Comment by lucent-sea** [comment]
I'm using the default cookie settings for ASP.NET Core 3.1.  Each middleware, such as Identity and Antiforgery, use their own default cookie settings.  You can find them here:  https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1

I have servers running on Windows behind IIS and on Ubuntu behind Nginx.  They're both using the recommended hosting scenarios, and the login works fine.

I can't change the cookie policy for everyone to satisfy a unique configuration.  You'll need to make changes on a fork to find a cookie policy that works for your setup.  You can read more about differing hosting scenarios here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-3.1
