### ISSUE TITLE
Update from August to September build results in "connection error:" message when trying to take control

### ISSUE THREAD

**Issue by meyerje** [lucent-sea/Remotely#124]
After updating from v2020.08.09.1114 Release to the v2020.09.09.1651 Release connection attempts to endpoints results in a error message stating "connection error:".
 
1. Setup install on Windows Server 2016 using v2020.08.09.1114 release and add clients.
2. Update v2020.08.09.1114 to the v2020.09.09.1651 release and attempt to connect to clients.
3. Note that the remote connection screen now shows a "connection error:" message.

**Expected behavior**
Connections should continue to work.

**Desktop (please complete the following information):**
 - OS: Windows 7, 10, and Server 2016
 - Browser Chrome and FF
 - Version latest

**Additional context**
I can redeploy if that's possible but it seems as if something went wrong once the server updated the agents.

**Comment by meyerje** [comment]
I redeployed the agent to a handful of endpoints and that got them reporting back into the server.  I'm able to run cmd / ps command against them but continue to get the "connection error:" message when trying to take control.
![error](https://user-images.githubusercontent.com/14101792/92844808-dfec8b80-f3ab-11ea-9e4a-e045fc21f3b0.png)

**Comment by lucent-sea** [comment]
Did the agents update successfully?  Do the versions for server and agents match?

Server Version can be found in About Remotely link at the bottom of the main page.

Agent Version can be checked by clicking the Edit icon on the device row, or using the `GetVersion` command.

If the versions match, try clearing the browser cache while on the remote control page.  I was hoping to have the caching issue fixed this release, but ran into an issue with SystemJS.  It appears they're not intent on fixing it.  I'll look for alternatives later.

If you're still having issues, check the logs on the agent right after it disconnects.  There might be something indicative in there.  `GetLogs` from the console, or check the C:\Windows\Temp\Remotely_Logs.log file.

Also check the server logs.  Account - Server Logs.

**Comment by meyerje** [comment]
I checked the agent and server version which did match.  After clearing the browser cache the connection started working again.  I will note the log information should the issue present itself again.  Thanks!

**Comment by lucent-sea** [comment]
No problem!
