### ISSUE TITLE
[Feature] - Bi-directional file transfer during remote control.

### ISSUE THREAD

**Issue by lucent-sea** [lucent-sea/Remotely#126]
This has been committed from FeatureUpvote.

The File Transfer button on the remote control's sidebar will prompt for download or upload, allowing for download of remote files.

(Note: This can already be done on the console via UploadFiles and DownloadFile commands.)

**Comment by jvanegasv** [comment]
awsome!!!!

**Comment by lucent-sea** [comment]
Completed.
