### ISSUE TITLE
RDP Resolution Improvement

### ISSUE THREAD

**Issue by umar-ulabs** [lucent-sea/Remotely#130]
The images/frames sent over to browser tend to be low resolution/blur. Is there a way to improve the quality?
Thank you

**Comment by lucent-sea** [comment]
The resolution will be whatever resolution is used for the RDP session.  Increase the resolution for the RDP session, and the resolution will increase for Remotely.

In normal mode, you can also try increasing the quality in the sidebar.  However, anything beyond the default quality setting usually has diminishing returns.

You can also try switching to Stream Mode in the sidebar if you get a P2P connection.  This will stop my hand-rolled image diffing and switch to WebRTC's video streaming.
