### ISSUE TITLE
is there a chance of a update feature, the current wget  is not working

### ISSUE THREAD

**Issue by rhinopctec** [lucent-sea/Remotely#131]

**Comment by lucent-sea** [comment]
Uh...  What?

**Comment by rhinopctec** [comment]
I tried to install the Remotely app on a Ubuntu vm box with the latest
version and the wget command comes back with an error

**Comment by lucent-sea** [comment]
Oh!  I'm sorry.  I understand now.  I replaced my username a while back.

I created a new release.  For existing SH files, replace "jay-rad" with "lucent-sea" in the URLs.

**Comment by rhinopctec** [comment]
Thanks but am having issues installing Remotely on a CentOS any tips you
can offer would be greatly appreciated, am using a VM with older versions
worked flawlessly but now not so easy?

**Comment by rhinopctec** [comment]
Am getting this error on a CentOS VM

Install.sh [following]
--2020-09-30 17:17:05--
https://github.com/lucent-sea/Remotely/releases/download/v2020.09.28.1739/Rem
                             otely_Server_Install.sh
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2020-09-30 17:17:05 ERROR 404: Not Found.

[root@li1032-188 ~]# wget
https://github.com/Jay-Rad/Remotely/releases/download/v2020.09.28.1739/Remotely_Server_Install.
          sh
--2020-09-30 17:17:15--
https://github.com/Jay-Rad/Remotely/releases/download/v2020.09.28.1739/Remotely_Server_Install.s
          h
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location:
https://github.com/lucent-sea/Remotely/releases/download/v2020.09.28.1739/Remotely_Server_Install.sh
[following            ]
--2020-09-30 17:17:15--
https://github.com/lucent-sea/Remotely/releases/download/v2020.09.28.1739/Remotely_Server_Instal
          l.sh
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2020-09-30 17:17:15 ERROR 404: Not Found.

**Comment by lucent-sea** [comment]
The file names have changed.  Please find the correct URL for the file you're trying to get:  https://github.com/lucent-sea/Remotely/releases
