### ISSUE TITLE
Update Process?

### ISSUE THREAD

**Issue by tedtms** [lucent-sea/Remotely#138]
Hey Jay,

Thanks again for the Arch support! I'm in process of testing it, but I've realized that I'm not sure how to properly perform an upgrade of the Ubuntu server installation. 

I've been able to do it by doing a fresh install and then copying Remotely.db and my appsettings file into the new directory, but I've found that all of my clients fail to connect after I do that. I've attached a sample log file from the one machine I have local access to. And I've also confirmed that the Organization ID was retained and is correct in the updated server.

Is the only way to get around this to essentially upgrade the clients first, then upgrade the server?

Thanks,
Ted

EDIT: Forgot the logs -- [logsample.txt](https://github.com/lucent-sea/Remotely/files/5324244/logsample.txt)

**Comment by tedtms** [comment]
FYI just tried extracting the installer from my new server version and running it on my local machine, then switching to the updated version on my server, and my local client still shows up offline with the same local logs.

**Comment by lucent-sea** [comment]
You just need to rsync the new application files to the website directory (e.g. /var/www/remotely/), then restart the Remotely service.  The clients will update automatically.  As long as you've created `appsettings.Production.json`, nothing will be overwritten.

Or you can re-run the server install script.

Or you can deploy from one of the GitHub Actions workflows (https://github.com/lucent-sea/Remotely/tree/master/.github/workflows).  For SSH deployment, you'll need to restart the service afterward.

**Comment by swilkey** [comment]
Thanks Jared, this is really useful to know - can it be added to the readme.md?  I've been waiting several releases and then doing a complete reinstall, but to know there is an easier way is wonderful.  Regards,
Stephen

**Comment by rhinopctec** [comment]
Am really lost on how to Update the Remotely Application could someone walk me through it or maybe some Documentation maybe
