### ISSUE TITLE
[Enhancement] Options for disabling registration

### ISSUE THREAD

**Issue by Nonobis** [lucent-sea/Remotely#142]
Hello,

Could you add an options for disabling new user registration via configuration screen, or do you accept pull request ?

PS : If you want i have made a docker for instaling last release automatically.

Thanks

**Comment by lucent-sea** [comment]
This is done via the MaxOrganizationCount property.

Thanks for the offer for the Docker file.  However, I have an automated build pipeline that builds and deploys from source, which allows for hard-coding the server host name into the desktop clients and installer.
