### ISSUE TITLE
Can some one educate me on how to update Remotely from old version to latest without losing. All the settings and client info

### ISSUE THREAD

**Issue by rhinopctec** [lucent-sea/Remotely#144]
Can some one educate me on how to update Remotely from old version to latest without losing. All the settings and client info or losing cert.

**Comment by meyerje** [comment]
It's in the README.md of the github page: https://github.com/lucent-sea/Remotely#upgrading

The only caveat I would bring up is that the project is a hobby and support for moving up past 1-2 releases is not guaranteed.  To mitigate this I simply grab every release and upgrade to the next giving enough time for all agents to also upgrade.  Then I move on if behind by several until the installed version is caught up to the github releases.

**Comment by lucent-sea** [comment]
What @meyerje said.  :)
