### ISSUE TITLE
Optionally write the Session URL (to stdout/file) when starting the Instant Client

### ISSUE THREAD

**Issue by hubermarkus** [lucent-sea/Remotely#146]
if have tested to add it just to the SessionIDChanged event, works, but maybe not a nice place, and having behaviour optional (via command line option -WriteSessionURL {stdout|file}) would be great.
      

 private void SessionIDChanged(object sender, string sessionID)
        {
            var formattedSessionID = "";
            for (var i = 0; i < sessionID.Length; i += 3)
            {
                formattedSessionID += sessionID.Substring(i, 3) + " ";
            }
            SessionID = formattedSessionID.Trim();
            **Console.WriteLine("SessionID: {0}", sessionID);
            Console.WriteLine("URL: {0}", $"{Host}/RemoteControl?sessionID={SessionID?.Replace(" ", "")}");**

        }

**Comment by lucent-sea** [comment]
As mentioned in the other issue, there's already an established way of gaining unattended access.

With the Agent running, you can call `/api/remotecontrol/{deviceId}` to get a one-time remote control URL.  You'll need to create an API token and include it in the Authorization header in "{token}:{secret}" format.  It expires after 30 seconds.

**Comment by hubermarkus** [comment]
Hi lucent, sorry for the late answer, but we don't want to install the agent, we just want to use the instant client (e.b. like the Teamviewer Instant Client). And therefore we just need something that outputs the ID to stdout or into an file.
