### ISSUE TITLE
add the abiliy to start the "RemotelyService" in a NON Service Mode (but using a the SYSTEM Account)

### ISSUE THREAD

**Issue by hubermarkus** [lucent-sea/Remotely#148]
We are want to integrate remotely into our Cloud RMM Solution (www.xeox.com) and we would like to have the ability to start the Service Functionality (Switches between user connection, connect to the console/admin session) also without to install the service.

We just want to start it temporarily (with command line options).
Our Agent is running as system user, so the ACL should be similar when running as service.

**Comment by lucent-sea** [comment]
The Agent can now be started outside of a service.

**Comment by hubermarkus** [comment]
Hi, sorry, for the late answer, how can we start the RemotelyService in a NON Service Mode (e.g.) but still having all features of the "Service Mode) (connect to console session, switch btw. sessions,etc). Is there a command line switch for this?

**Comment by lucent-sea** [comment]
Honestly, I'm not sure if this would work.  But here's what you'd need to do to test it.

- Download the appropriate ZIP package (e.g. https://app.remotely.one/Content/Remotely-Win10-x64.zip)
- Extract the contents somewhere.
- Add a `ConnectionInfo.json` file in the same directory with the required JSON data.
  - DeviceID should be a GUID.
  - Host should be the server URL (e.g. "https://app.remotely.one").
  - OrganizationID should be your organization ID on the Remotely server.
  - ServerVerificationToken should be null or empty string initially.  The agent will add a value the first time it connects.
- From your service, start  `Remotely_Agent.exe` and see what happens.
