### ISSUE TITLE
SSL/Local Installation Question

### ISSUE THREAD

**Issue by sinichi19** [lucent-sea/Remotely#149]
Good Day,

1st nice work and thank you.
(Ubuntu_server_install.sh)

Want to use only on local connection and dont have domain its possible? when I install on ubuntu server.
Or if there is option to not install the certbot for SSL if i have own certificate.

Thank you More power

**Comment by meyerje** [comment]
Edit the install script (https://github.com/lucent-sea/Remotely/blob/master/Utilities/Ubuntu_Server_Install.sh) and remove the last lines where certbot is installed, as well as add your 443 personal certs to the nginx config section further up.  I have not tested this but it should work.

**Comment by sinichi19** [comment]
> Edit the install script (https://github.com/lucent-sea/Remotely/blob/master/Utilities/Ubuntu_Server_Install.sh) and remove the last lines where certbot is installed, as well as add your 443 personal certs to the nginx config section further up. I have not tested this but it should work.

thank you sir, will try this

God bless and more power
