### ISSUE TITLE
Instant support client question

### ISSUE THREAD

**Issue by sinichi19** [lucent-sea/Remotely#153]
Good Day,

sorry for this question..

My question is if there is an option or way to modified the instant support client in windows. Like the change the default Remotely and change to organization name of the server, logo and already setup the hostname and cant change by the user.

thank you.

**Comment by stevesobol** [comment]
On 2020-10-24 04:40, Sinichi wrote:

> Good Day, 
> 
> sorry for this question.. 
> 
> My question is if there is an option or way to modified the instant support client in windows. Like the change the default Remotely and change to organization name of the server, logo and already setup and cant change by the user.

I'm doing exactly that, and making some other modifications as well
(changes to branding and functionality that make the client better
equipped to handle my specific needs).

**Comment by lucent-sea** [comment]
No, there is no branding service, and I have no plans to create one for now.

As @stevesobol said, you'll need to fork the repo and make customizations in the source code.
