### ISSUE TITLE
Elevate to Service Question

### ISSUE THREAD

**Issue by sinichi19** [lucent-sea/Remotely#154]
Good Day,

Looking for your kind assistance,

Dont know if this normal when i used remote desktop.exe and click the Elevate to Service it will disconnected because the session ID of the computer is also changed. I need to request again the session ID 

Expected behavior is when I choose to elevate to service stay connected and not change the session ID
Only change when I closed the Remote_desktop.exe

Thank You and More Power

**Comment by sinichi19** [comment]
or if there is an option when I build new .exe is already Elevated to service like the server is already hard coded to the exe.

**Comment by lucent-sea** [comment]
When the process is elevated to a service, it has to be closed and re-opened.  It's expected that the session ID changes.

When the UI is visible, someone needs to be sitting at the remote computer to give you the session ID, then click the OK button to accept the connection.

If you want unattended access, you need to install the service.

There's no in-between.
