### ISSUE TITLE
Remotely Linux Server Question

### ISSUE THREAD

**Issue by sinichi19** [lucent-sea/Remotely#156]
Good Day,

To All,

Sorry for this question know that is not part of this project but looking only for your kind assistance.

Make some edit in source code and want to install in ubuntu from edited source code and I read in other post that need to recompile. I'm not good to this and want to try. 

My question or request is how can I install Remotely server from my edited source code to ubuntu

or Requesting to educate me how make this
![image](https://user-images.githubusercontent.com/44279612/97401603-0f3f6380-192c-11eb-8707-e88f0f7edc7f.png)

Thank You and More Power

**Comment by sinichi19** [comment]
I added this to server.csproj
![image](https://user-images.githubusercontent.com/44279612/97414714-4ff4a800-193f-11eb-97b5-d0427c1ff969.png)
 then publish 

after test is working but not sure if i missing something or to work perfectly

Thank You

**Comment by Nil0x** [comment]
Follow the instrusctions under "Build Instructions (Windows 10) " in the README file ( https://github.com/lucent-sea/Remotely/blob/master/README.md ) . That's what the rid is regarding. I've confirmed that those instructions work by the way.

**Comment by sinichi19** [comment]
> Follow the instrusctions under "Build Instructions (Windows 10) " in the README file ( https://github.com/lucent-sea/Remotely/blob/master/README.md ) . That's what the rid is regarding. I've confirmed that those instructions work by the way.

@Nil0x  Thank you very much
