### ISSUE TITLE
typo in Linux link on home page

### ISSUE THREAD

**Issue by tompatulpan** [lucent-sea/Remotely#157]
Hi,
a typo in the link to linux client on "https://remotely.one/#portableClients"
The link "https://app.remotely.one//Downloads/Remotely_Desktop" has two "slashes"

Thanks for a very good alternative!

**Comment by Nil0x** [comment]
I think @lucent-sea fixed it. 

![Screenshot from 2020-10-31 11-20-44](https://user-images.githubusercontent.com/73607515/97783001-3d5eb680-1b6b-11eb-8c48-ec97f4814509.png)

**Comment by lucent-sea** [comment]
I did fix this, but didn't have time to respond.  :)  Thank you for mentioning it!
