### ISSUE TITLE
Client connection issue on latest release

### ISSUE THREAD

**Issue by tedtms** [lucent-sea/Remotely#160]
Hey,

I've built a fresh install on my Ubuntu server using the latest release, 2020.10.24.0945. On my client machines however, the installation succeeds but the clients never connect to the server instance. Checking the logs, I get these errors, which repeat endlessly:

`2020-11-01 22:28:51.596	[Info]	Service Updater: Version is current.`
`2020-11-01 22:29:01.836	[Warning]	Failed to connect to server.  Internet connection may be unavailable.`
`2020-11-01 22:29:01.842	[Warning]	Unable to complete handshake with the server due to an error: Handshake was canceled.	   at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at Remotely.Agent.Services.AgentSocket.Connect() in C:\ProgramData\BuildAgent\_work\1\s\Agent\Services\AgentSocket.cs:line 61	Microsoft.AspNetCore.SignalR.Client.Core`
`2020-11-01 22:29:02.196	[Info]	Service Updater: Version is current.`

Previously, I was running 2020.03.27.0404 and did not have this problem. But I'd really like to use the new features, and I was having trouble upgrading so I performed a fresh install. For more context, I'm running Remotely behind an SSL NGINX proxy on another machine so I'm using the `Environment=ASPNETCORE_URLS=http://*:5000` option in my systemd service and I'm not running NGINX or certbot/SSL on my Remotely machine.

Any help would be appreciated!

Cheers,
Ted

**Comment by tedtms** [comment]
Also worth noting, I performed a test client install on a fresh machine that had never had Remotely Client installed on it, and experienced the same errors.

**Comment by lucent-sea** [comment]
I've reverted some changes to the Nginx config.  You can try that:  https://github.com/lucent-sea/Remotely/blob/master/Utilities/Ubuntu_Server_Install.sh

You'll also want to make sure KnownProxies is configured, if you haven't already.

But if that doesn't help, I'm afraid there's not much I can do.  Everything is working on my servers, and this is the first report I've gotten of any issues.

**Comment by tedtms** [comment]
Ah, perfect. The nginx changes were what I needed to make, thank you. A quick note though, for some reason I was getting a blank page after making the changes, but removing all of the backward slashes (\) on entries like `proxy_set_header Connection \"upgrade\";` fixed the problem.

Cheers,
Ted
