### ISSUE TITLE
Clipboard not supported in this Browser?

### ISSUE THREAD

**Issue by tedtms** [lucent-sea/Remotely#164]
Hey Lucent,

Since upgrading to your latest October version, I've noticed that the clipboard function no longer works in Firefox. Is there a specific limitation causing this? It worked fine in previous versions.

**Comment by lucent-sea** [comment]
Firefox is able to write text to the clipboard, but it doesn't allow scripts to read from it.  It's only allowed in browser extensions.

Here's the API I'm using.  See the compatibility chart at the bottom:  https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText

**Comment by tedtms** [comment]
If FF can write to the clipboard, then shouldn't the "Type Clipboard" button still work? The vast majority of my use cases involve sending clipboard text to the client machine, so it would be nice. Were you using a different API in earlier versions when Firefox worked fine?

**Comment by lucent-sea** [comment]
It's the other way around.  The browser would need to *read* your clipboard in order to send it to the remote computer for typing.

I think I've been using the same API for the whole time for reading the clipboard.  A while back, though, there used to be a text box to paste into, and that's how it was transferred.

**Comment by tedtms** [comment]
Oh, ok gotcha. That makes more sense... is it possible to restore the clipboard text box?

**Comment by lucent-sea** [comment]
No, I won't be reversing implementation.  I prefer having it this way.  Firefox often struggles to keep up with Chromium in terms of feature support, and I don't want to limit functionality to maintain compatibility with Firefox.  It also takes more time to develop if I'm having to test everything in two browsers.

On Edge/Chrome, I also have the clipboard transferring back and forth automatically.  You can Ctrl + C on either end and Ctrl + V on the other.  With Firefox, it can only work one-way.
