### ISSUE TITLE
Problem when running commands to remote Windows endpoints

### ISSUE THREAD

**Issue by mntsupport** [lucent-sea/Remotely#165]
I just set up this platform today and so far I think it's the bees knees!

I have it installed on DigitalOcean's basic droplet, Ubuntu 18.04

I'm having issues when trying to run commands on a remote Windows PC. When I run the CMD command `start firefox` I check task manager and I can see that Firefox did indeed launch, but no window is displayed.

Thanks in advance!

The XML from the job on the server shows the following(The body is in the attached .txt. It was too big to paste):

`An unhandled exception occurred while processing the request.
SerializationException: Object graph for type 'System.Collections.Generic.HashSet`1[[Remotely.Shared.Models.CommandResult, Remotely_Shared, Version=2020.11.7.1631, Culture=neutral, PublicKeyToken=null]]' contains cycles and cannot be serialized if references are not tracked. Consider using the DataContractAttribute with the IsReference property set to true.
System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnHandleReference(XmlWriterDelegator xmlWriter, object obj, bool canContainCyclicReference)`

[Remotely.txt](https://github.com/lucent-sea/Remotely/files/5513560/Remotely.txt)

**Comment by swilkey** [comment]
Hi mntsupport,

I agree.  Remotely is a great tool.

Your question was a little ambiguous so I want to check - when you say you are running commands remotely are you doing it through the console command line section or are you doing it with a full remote control session?

My understanding is this - when you are remote controlling the computer it takes the identity of the currently logged on user and anything you do will be visible to them.  However, if you are running things on the command line using the console it is expected that what you are running requires no user interaction, therefore if you run start firefox it does indeed run it, but not in a space that can interact with the user.  This functionality is designed for being able to run scripts and things that operate without requiring interaction with the user - a script or command line tool will return the results to you at the console, but anything requiring a GUI interface will run and not be able to return anything to you or the user.

**Comment by mntsupport** [comment]
Hey!

My apologies, this is through the Console cmd section.

Thank you for that explanation. It looks like I was trying to to use it in the incorrect manner. Thank you for this clarification!

**Comment by lucent-sea** [comment]
Hiya! 

@swilkey is correct. The process that runs the script is a Windows service in session 0.  This allows it to run when no one is logged in, and it can't interact with a user's desktop.
