### ISSUE TITLE
IPv4-mapped IPv6 addresses have ::ffff: prefix, Known Proxies doesn't seem to work

### ISSUE THREAD

**Issue by alexdelifer** [lucent-sea/Remotely#166]
Hi there!

Let me start with the fact that I love this tool so so much, it's really made it easier to manage my home servers, and remote machines, as well as provide support to my mum. I do have an issue though, while not major, lets call it a nice to have.

Disclaimer, I made a docker container for this server, any issue might be my own negligence.
https://github.com/alexdelifer/docker-remotely
https://hub.docker.com/r/delifer/remotely

Certain reverse proxies do some weird stuff with IPv4-mapped IPv6 addresses.
This Wikipedia gives an overview of how those work if you never heard of that like me. https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses 

I'm using [cloudflared](https://github.com/cloudflare/cloudflared) which is a reverse proxy that kind of works like an ssh tunnel or ngrok if you've heard of that. It lets you have a subdomain map to a service without opening a port on your firewall by first making an outgoing connection and waiting for traffic to flow backwards.

When my agents connect to my server, the IPs shown are not the X-Forwarded-For IPs, but instead are shown as: `::ffff:172.16.63.6`

Where 172.16.63.6 is the IP of the cloudflared "reverse proxy".

![image](https://user-images.githubusercontent.com/1463882/99004982-f6c76f80-250d-11eb-9fbb-e3a978b66206.png)

My other services that use this same tool to reverse proxy wind up showing the proper public IP, not 172.16.63.6, and no ::ffff: prefix. I'm not sure if maybe the prefix breaking something that makes it not resolve the X-Forwarded-For, or something else entirely. In my mind, something with the trusted proxy box doesn't like the prefix so I can't add it properly.

Other posts about this kind of issue says it's related to the app itself and not the reverse proxy, if you have any ideas I'd love to hear them. I couldn't find anywhere in the code where it uses the x-forwarded-for field for the Public IP field.

This page has some details about what to do with the ffff prefix that might help, I know PowerShell pretty well but C# is on another level for me:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0#configuration-for-an-ipv4-address-represented-as-an-ipv6-address 

These guys seem to get along fine by just chopping off the prefix:
https://stackoverflow.com/questions/31100703/stripping-ffff-prefix-from-request-connection-remoteaddress-nodejs

I think if the server knew what to do with the ::ffff: prefix, then I could add the proxy to the Known Proxies box in server config and everything would work beautifully.

Also, does the the Known Proxies box accept a subnet range or a domain name? My docker container might spawn with any IP within the 172.16.63.0/24 subnet, it would be nice if I could just enter that subnet and it work, otherwise I can add every IP...

Thanks and no hard feelings if you can't get to this!

**Comment by lucent-sea** [comment]
Hello.

I had a header forward limit to set to 2, which might be what was causing it.  I removed the limit in the last commit.

The KnownProxies array only accepts exact IP matches.  KnownNetworks can be used to specify ranges (in CIDR format), but I don't have it as an option.

As for the IP display format, I added the below to check if it's IPv4-Mapped-to-IPv6. If so, it converts it to IPv4 format.

Let me know if the removal of the header limit helped!

```
var ip = Context.GetHttpContext()?.Connection?.RemoteIpAddress;
if (ip != null && ip.IsIPv4MappedToIPv6)
{
    ip = ip.MapToIPv4();
}
device.PublicIP = ip?.ToString();
```

**Comment by alexdelifer** [comment]
That was quick!
I'll let you know if it works as soon as I figure out how to build the Linux server.
Haven't used VS in a hot minute.

Thank you!

**Comment by alexdelifer** [comment]
You sir are a wizard.
It works beautifully. I now see both IPv4 and IPv6 addresses, they're all the proper Public IP.

I had already added every IP from 1 to 254 within that subnet, so it worked right away. No worries about that, I should just shorten the subnet to a /29 or something to make it less annoying in the future.

Thank you so much!

P.S. it took like 2 minutes to figure out how to build it, your Publish.ps1 script is awesome as well.

**Comment by lucent-sea** [comment]
Awesome! I'm glad it worked out. :)

And thank you for the sponsorship! It's very much appreciated.
