### ISSUE TITLE
Error when changing the current username to an existing username with a capital character

### ISSUE THREAD

**Issue by tweidinger** [lucent-sea/Remotely#168]
When changing the own username to the same as another existing (admin) account but with a capital character,
the application responds with 
```
Request URL: https://app.remotely.one/Identity/Account/Manage
Request Method: POST
Status Code: 500 
```

Example user change request, assuming _admin@remotely.one_ already exists.
```
Input.Email: Admin@remotely.one
Input.DisplayName: 
Input.PhoneNumber: 
```

I tried this on the demo site and did not investigate locally.
The sources indicate a normalization issue, which is not handled outside of the database layer but I did not look further.

This should be handled more gracefully and show me that this user already exists.

**Comment by lucent-sea** [comment]
Thanks,  Added in 1d3edf69368cd7c27f138f7c7bded72f953fa61f.
