### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by rescaux** [lucent-sea/Remotely#169]
Little question: is it possible to login through an AD/LDAP server?

**Comment by lucent-sea** [comment]
Not with the current implementation, no.

**Comment by rescaux** [comment]
Is there any chance this will be implemented some time in (near) future?

**Comment by lucent-sea** [comment]
I've no intention of working on it, no.  At least not for free.  It's not worth sacrificing time with my kids for large features when I have no use for them.

**Comment by Makr91** [comment]
A solution would be to use something like Authelia and a load balancer like HAproxy and put it behind that.
