### ISSUE TITLE
Error after Build - There was an unhandled exception

### ISSUE THREAD

**Issue by RedJohn14** [lucent-sea/Remotely#170]
Hello,

I would like to use your great software. I must Build the clients (windows, linux), otherwise it will ask for a server address on start up the client.

I have build like this here:

**powershell -f Publish.ps1 -outdir C:\output1 -rid linux-x64 -hostname https://mydomain.com**

After Build is finisehd and a try to start the **Remotely_Desktop.exe in Win-x64** I have an error like this:

**There was an unhandled exception**

I can not start the clients on my or on other computers. Any ideas what my mistake is? I have also removed everything and build a new one but with same result and error message.

Other question, is it possible to copy the clients to a running server? I have running server like this docker project here:

https://github.com/alexdelifer/docker-remotely

But I need to set the hostnames, otherwise the "quick support" ask for server url.

Regards!

**Comment by lucent-sea** [comment]
There isn't enough information here.  I need a stack trace.  If I can't quickly and easily reproduce the issue on my own computers, I won't work on it.

**Comment by ndrosis** [comment]
HI @RedJohn14 

remove NET SDK 5 from visual studio 2019 and install below
sdk core 3.1 X64 [https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.404-windows-x64-installer](url)
x64 Runtime 3.1 [https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-3.0.3-windows-x64-installer](url)
