### ISSUE TITLE
Middle mouse button not registering on remote computers

### ISSUE THREAD

**Issue by cassycoha** [lucent-sea/Remotely#171]
I noticed that middle mouse button inputs do not register on the remote computer -- just wondering if there is a way to add our own support for forwarding additional key / button events to the remote computer, or if this is a hard limitation.

**Comment by lucent-sea** [comment]
I just added it.  But in my tests, it's acting kinda weird.  It works as expected at first.  For example, middle-clicking in the browser and doing universal scroll.  But after clicking again to stop scrolling, mouse input seems to be "stuck" in that window.  It can't target anything else until sending Ctrl+Alt+Del.

I didn't test it very much, though.  Might look into it more later.
