### ISSUE TITLE
blinking screen with different screen orientation

### ISSUE THREAD

**Issue by BlijeGub** [lucent-sea/Remotely#173]
The remote control keeps blinking and turning black when a laptop or pc is in tablet mode. Unless I keep moving the mouse the screen turns black if anything changes on screen. Remote control is almost unusable.

**Comment by BlijeGub** [comment]
Seems to be a problem with auto rotation instead of tablet mode.

**Comment by lucent-sea** [comment]
I made a change to handle screen rotation.

**Comment by BlijeGub** [comment]
Thank you very much now I can take over all my systems. It still seems broken for me when a screen has been rotated 180 degrees. But that was less important for me.
