### ISSUE TITLE
Override UAC ( unable to operate if run anything run as admin. )

### ISSUE THREAD

**Issue by wikimao** [lucent-sea/Remotely#174]
Override UAC ( unable to operate if run anything run as admin. )

- logged in as non-admin user.
- run cmd or powershell as admin. ( you will see the blank screen ) 
- if username or password prompt, unable to write.

**Comment by lucent-sea** [comment]
This is by design.

**Comment by wikimao** [comment]
is there any way to input admin username password, once prompt?
