### ISSUE TITLE
Including server URL in Instant Support Client, 

### ISSUE THREAD

**Issue by ThelloD** [lucent-sea/Remotely#180]
I've spent some time testing Remotely and it looks really very promising, thank you for this great project!

However, I've got a couple of questions for which I couldn't find a clear answer even after searching on GitHub and Reddit a lot. Maybe for some of those creating a feature request would make more sense, but since I'm not sure whether it's already implemented or not I'd like to ask first, hope you don't mind if I raise the questions here - maybe this could be valuable for others as  well.

- The Instant Support Clients (Remotely_Desktop.exe) are very handy, but the user still has to enter the server URL on first start. Is there any way to include the server URL in the .exe, so the user only has to download and start the .exe and tell me the ID?

- The Instant Support Client always requests extended privileges when it's started and the Windows UAC dialog opens and asks for confirmation. I'm aware that there are cases where elevated privileges are required and otherwise some applications cannot be accessed by Remotely. However, there are also plenty cases where support is needed but no elevated privileges are required and forcing the user to grant these privileges could be seen as dubious by the user. Further, the application already has the "Elevate to Admin" function when the gear icon is pressed, however this entry is (always) greyed out since the application already (and always) has the elevated privileges. Is there any way to run the Instant Support client with only regular user permissions for cases where it's not needed?

- The download section shows the installation command for the resident agents after logging in, such as `Remotely_Installer.exe -install -quiet -organizationid "0b3d706b-9c5d-41e6-8ae9-5720d16324e6" -serverurl "https://remotely.mytechshop.com"`. Are these parameters (cannot and URL) hardcoded, or can they be changed so that one only has to copy & paste the command from the web application?

In case the Instant Support Clients does not yet support including the server URL within the .exe, maybe it could be passed by a custom file name similar to `organizationid` for the Windows installer? (Would require some sort of encoding, e.g. something similar to base64 but without the `/` character)

PS: I didn't compile the project but I'm using a Dockerfile that primarily relies on `Remotely_Server_Linux-x64.zip` from the releases (v2020.11.25.1712), so maybe I'm missing out of some of the available customizations because of that?

**Comment by lucent-sea** [comment]
You can compile it yourself to hard-code the server URL. This is covered in the Readme.

There's no way for me to distribute pre-compiled EXEs that have server URLs hard-coded. I'm trying to find the words to explain why, but if you think about it, it should be pretty obvious. Not trying to sound rude here. It's just kinda logically impossible. 

UAC behavior can be changed in the app manifest. I currently have it set to "highest available."  The file has comments explaining each option. Be aware that "running as a normal user" means you wouldn't be able to interact with Task Monitor, Device Manager, and several other windows that automatically run with elevation.

Not sure what you mean about the installer.

**Comment by ThelloD** [comment]
Thank you for the fast reply!

Somehow I indeed missed the instructions in the workflows/XY.yml files, sorry for that.
Great to hear that the server URL can be easily pre-definied via the workflows, will definitely take a closer look.

I'm aware about the limitations if the application is executed as normal user. For changing system settings it's of course crucial, for helping setting up an email account in Outlook or similar tasks normal user rights usually are sufficient. (Btw, AnyDesk has a nice solution here, session is started with normal privileges but can be elevated on-demand, session reconnects automatically and everything happens nearly transparently.)

Thanks for pointing me to the application manifest, I'll change this in my fork then. I assume the manifests for both `Desktop.Win.Wrapper/` and `Desktop.Win` have to be changed, right?

Regarding the installer, it's really not that important. I was talking about the `/Agents` endpoint where not only download URLs are presented but also commands for the quiet installer etc. On this page the commands are using some default parameters such as `organizationid "0b3d706b-9c5d-41e6-8ae9-5720d16324e6" -serverurl "https://remotely.mytechshop.com"`. I wondered if it's on purpose, that only exemplary values are stated on the web application instead of real ones, respectively if this page could/should be dynamic and show the real organization-ID etc., so that the command can be simply copied from the browser without having to adapt any parameters.
Or with other words, I wondered if this page is indeed static or if I missed to configure something so that these values are parameter values are replaced by real values.
However, looking at `/Server/Pages/Agents.cshtml` it seems that currently these values are indeed static and hard-coded to exemplary values.

Regarding inclusion of the URL in the EXEs, of course distributing numerous pre-compiled EXEs really wouldn't make sense. However, I think other solutions than setting the URL during compile time exist as well. A couple of examples:
- Including the (encoded) URL in the file name (similiar to what you're already doing via `/API/ClientDownloads/Windows` and the resulting file name that includes the organization id)
- Adding the server URL as metadata to the file or maybe even some binary patching before the file is downloaded
- Using command line arguments and wrapping the application together with the server URL as argument, similar to common exe packers such as [UPX](https://github.com/upx/upx).

So please don't get me wrong, I think for me the approach via compilation or GitHub workflows should work fine. But not having to compile from source would simplify the deployment process and help mass adoption of the tool, so maybe this could be considered as a goal for some time in the future ;)

**Comment by ThelloD** [comment]
Deployment via GitHub workflows worked fine, the server URL is now hard-coded within the binaries.
(As a note for anyone curious, for testing whether the binary was updated successfully, delete the file `C:\Users\<USER>\AppData\Roaming\Remotely\Config.json` and the folder `C:\Users\Bernhard\AppData\Local\Temp\Remotely_Desktop` before starting the client.)

I've also changed the manifest of the Windows clients for using normal user privileges in `Desktop.Win/app.manifest` and `Desktop.Win.Wrapper/Properties/app.manifest` by replacing line 19 with the following line:
```
<requestedExecutionLevel level="asInvoker" uiAccess="false" />
```

The content on `/Agents` still shows the exemplary values such as "https://remotely.mytechshop.com" etc., but looking at the source I think that the page is static by design.

Although I think there is still some room for improvement regarding the download page and the how URLs are stored in the .exe files, the current solution works very well for me, so I'm closing this issue.

**Comment by GitHub-Lover** [comment]
I want to bring an idea in, which is used on an other software. To **put hostname of the Server-URL in the name of the instant-binary-file**.

E.g. the name of the instant **Remotely_Desktop-```host=<host-ip-or-name>,relay=<relay-code>```.exe** the hostname and the relay-code can determine of the binary-file from the name of the file.

IMHO (I'm not a dev), two things have to be changed:

* the function, that the Instant binary will determine the hostname/server-URL and relay-code from the own file name (and safe it in config.json)
  * if there is not found in the name of the exe-file, then use hostname of config.json (AppData\Roaming\Remotely)
    * if no config.json file is around, show the input form to set the hostname (and safe it to config.json)
* when the instant binary is downloaded from download page set the name of the file (as proposed above)
