### ISSUE TITLE
Feature request ? (aka how do I delete a pc)

### ISSUE THREAD

**Issue by notadevcollins** [lucent-sea/Remotely#182]
I don't know if im just missing it, but I can't find and option to delete a pc that has been added ?

by the way this software is awesome!

**Comment by swilkey** [comment]
Select the PC, then switch to the console and type "remove" or "delete" 
I can't remember which it is but if you type help it will be obvious, or 
you could just try either and one of them will work.

------ Original Message ------

**Comment by notadevcollins** [comment]
thank you!
