### ISSUE TITLE
[Feature] View Only

### ISSUE THREAD

**Issue by dsinfinite** [lucent-sea/Remotely#185]
Can an option be added to enable view only mode?

**Comment by lucent-sea** [comment]
Added.  https://github.com/lucent-sea/Remotely/releases/tag/v2020.12.15.2015

**Comment by lucent-sea** [comment]
To expand on this, I've replaced the actions buttons for each device with a drop-down.  "View Only" is now one of the options.

![image](https://user-images.githubusercontent.com/20995508/102313473-9325cd00-3f25-11eb-9bb7-5816e6009e73.png)

It will add "&viewonly=true" query parameter when navigating to the remote control page, which will set view only mode.  It can be toggled on and off in the sidebar.

![image](https://user-images.githubusercontent.com/20995508/102313637-db44ef80-3f25-11eb-8b79-d0401f12febc.png)
