### ISSUE TITLE
A few observations from testing

### ISSUE THREAD

**Issue by Jonathan-Garber** [lucent-sea/Remotely#189]
Anti-Virus pops the installer as Malware however after setting excemptions deploying a resident agent via scripts worked fine and installed as expected.

Uninstall command from console wipes the program out but leaves the program listed in the "Add/Remove" programs list
it also leaves the folder in program files but that is not as unusual as having it left in the add/remove list. Lots of uninstalls leave their folder structure behind.

I also think there is a bug in organizations.
I have the default/first organization
I set organization limit to 2
I created a new organization
I then deleted this new organization
I tried to make another but registration is disabled and the button is gone even though I have only 1 actual organization.

I believe when I deleted the second organization it didn't fully clear and remove things to free up the system for a new one.

Just a couple of things observed. Nothing major.

**Comment by Jonathan-Garber** [comment]
Under "Server Config"
it still shows online devices count of 2 but devices total count of 1
I had a second device but uninstalled it. So it looks like these counts don't update here.

**Comment by lucent-sea** [comment]
Umm.  Weird.  I swore I wrote out a rather length reply to this.  I guess I forgot to hit the green button.

I'll summarize:

- There likely isn't anything I can do about AV warnings.  An app that records your keys, simulates keystrokes, and runs arbitrary scripts probably looks like a virus to most heuristics.  It's my understanding that commercial RMMs have to work directly with AV companies to get whitelisted.  Not something I have time/money/clout to do.
    - I've submitted a handful of requests to Microsoft to get whitelisted for SmartScreen and Windows Defender.  Never heard back. 
    - VirusTotal has an API for submitting false positives, though.  And their site says they work with AV vendors to get them whitelisted.  I don't know how effective it is, but you could try uploading to there as part of your build process.
- I've fixed the Add/Remove thing.  Thanks for pointing that out.  Forgot to update that command when I added the Uninstall entry.
- I didn't know I had a way to remove organizations.  How are you deleting it?
- When a device disconnects, it can take up to 30 seconds for the server to let go of the connection.  On Windows, anyway.  Might be longer on Linux behind Nginx.  Let me know if the device total doesn't ever update.  It doesn't persist the count in the database or anything.  It's read from an in-memory collection on the SignalR Hub, so if the count never updates, it probably means that Nginx is still holding onto the session.

**Comment by lucent-sea** [comment]
And again, thanks for the feedback!  :)

**Comment by swilkey** [comment]
Jared,

I develop an application for in house use in my organisation that Windows Defender doesn't like, so each time I release a new version I have to get it whitelisted.  I always submit it here https://www.microsoft.com/en-us/wdsi/filesubmission
I've had it whitelisted usually in less than 24 hours.  Maybe because remotely looks a bit like a keylogger it is tripping up the process, but I just wanted to check you were using the right link.
Regards,
Stephen

**Comment by Jonathan-Garber** [comment]
The anti-virus software was more of a comment/observation than a problem report. I run into it all the time with remote access tools.

**I didn't know I had a way to remove organizations. How are you deleting it?**
Primary account that registers and creates the organization and is admin of the organization. If that account owner deletes their account & they are the only admin for the organization I had thought it would remove the organization as well. I see now it just removes the user account and data but leaves the organization a ghost in the db.

**When a device disconnects, it can take up to 30 seconds for the server to let go of the connection. On Windows, anyway... etc..**

So this could have been a case of wait longer and see. I was sure it was still showing the counts for quite a while but I'll try to test this again later today.

**Comment by lucent-sea** [comment]
Cleaning up.  I'll re-open if any further issues are reported.
