### ISSUE TITLE
problem with windows agent

### ISSUE THREAD

**Issue by novawaves** [lucent-sea/Remotely#190]
hi,  i searched long for a thing like remotely but there is a issue with the windows 10 x64 agent. i can not install it. the log says:

2020-12-17 19:47:16.013	[Info]	Install started.
2020-12-17 19:47:16.548	[Info]	Backing up current installation.
2020-12-17 19:47:17.254	[Error]	Ungültiger URI: Das URI-Format konnte nicht bestimmt werden.	   bei System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   bei System.Uri..ctor(String uriString)
   bei System.Net.WebRequest.CreateHttp(String requestUriString)
   bei Remotely.Agent.Installer.Win.Services.InstallerService.<DownloadRemotelyAgent>d__22.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Remotely.Agent.Installer.Win.Services.InstallerService.<Install>d__13.MoveNext()	System
2020-12-17 19:47:17.268	[Info]	Restoring backup.

thx

**Comment by lucent-sea** [comment]
It appears the server URL being entered is not a valid http or https Uri.  I'll put in additional checks to warn about it.
