### ISSUE TITLE
Might be user error but I get error " Git is not recognized as the name...../Publish.ps1:36 char:22"

### ISSUE THREAD

**Issue by wayneburlingame** [lucent-sea/Remotely#192]
I apologize as it might indeed be me the user is the error...

But when I running this command after cloning repo:

`powershell -f C:\Users\User\Remotely\Utilities\Publish.ps1 -outdir C:\inetpub\remotely -rid win10-x64 -hostname https://support.wayneburlingame.com`

I get error:
`git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\User\Remotely\Utilities\Publish.ps1:36 char:22
+     $VersionString = git show -s --format=%ci
+                      ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException`

I could not figure out how to fix. I thought maybe part of the line just needed enclosed.

Thank You,
              Wayne

**Comment by lucent-sea** [comment]
Hmm.  I thought Git was always installed with Visual Studio and didn't need special mentioning.  I'll look at it again.

You can download GIt here:  https://git-scm.com/downloads

**Comment by lucent-sea** [comment]
Closing this as a solved problem.  Let me know if that's not the case.  :)
