### ISSUE TITLE
Edge, Chrome, Brave Bidirectional Clipboard doesn't seem to be working

### ISSUE THREAD

**Issue by Jonathan-Garber** [lucent-sea/Remotely#194]
So bi-directional doesn't seem to be working. Is bidirectional supported in Chromium based browsers?
I can paste from my host to the remote but cannot copy/paste anything from remote back to host.

**Comment by lucent-sea** [comment]
I've never tried Brave.  It's working for me on Edge, though.  On Firefox, it's one-way (to the remote host) by default.  It doesn't let you programmatically alter the clipboard, only read from it.  You change it in `about:config` by seting the `dom.events.asyncClipboard.dataTransfer` property to `true`.

**Comment by Jonathan-Garber** [comment]
I tried in all 3 browsers above, Bi-Directional won't work for me. I was connected to Win 7 x64 bit machine if that makes a difference. I'll try testing on other OS's later today.

**Comment by Jonathan-Garber** [comment]
Yea I cannot get it to work? Am I overlooking something?
Server is Ubuntu 20.04
I tried connecting to Windows 10.0.17763 & Windows 10.0.19041
Clipboard wouldn't work bi-directional on either test machine. I could copy into the machine by clicking the button to type the clipboard but I couldn't copy out of the machine.

**Comment by lucent-sea** [comment]
Does the site have permission in the browser?

![image](https://user-images.githubusercontent.com/20995508/103012182-0adc9480-44f0-11eb-932d-f79fe6f06a0c.png)

**Comment by Jonathan-Garber** [comment]
Yea permissions were first place I looked on Edge, Chrome, and Brave.

**Comment by Jonathan-Garber** [comment]
Weird part is, I was sure this worked the other night during a test. I just cannot make it work now.

**Comment by lucent-sea** [comment]
When I have more time (maybe on lunch today?), I'll create a special build that you can place in the application folder.  If there's an error, it'll spam the logs like crazy, but then I should be able to figure out what it is.

**Comment by Jonathan-Garber** [comment]
I don't know if this helps but i've confirmed it with testing a few times now.

I have two organizations. A and B  (A was the first account/organization created in the system)
The clipboard works when I remote into systems listed in A.
If I log off A and log into B then remote into a machine the clipboard won't work bi-directional

I log off B and log back into A the clipboard still works as expected.

So simple recap
Organization A: Clipboard Works BiDirectional
Organziation B: Clipboard is only one-way

**Comment by lucent-sea** [comment]
I've run out of time tonight to look at this.  I'll try this weekend.

There aren't any settings that explicitly change clipboard behavior on an organization level.  So I'm not sure why that would happen.

**Comment by Jonathan-Garber** [comment]
I'll repeat the test in a private tab tomorrow in case something in cache
or history is doing something funky.

**Comment by lucent-sea** [comment]
Here's a copy that should spam your logs if it's having errors trying to read the clipboard.  Just replace the contents of `C:\Program Files\Remotely\Desktop` with these files.

https://www.dropbox.com/s/r1nxgwd0dwtr5ge/Desktop.zip?dl=0

**Comment by Jonathan-Garber** [comment]
Ok so this makes zero sense to me.
I tested this yesterday twice like above Clipboard was not working
I tested this today in private tab same setup, clipboard didn't work

So
I copied the original Desktop files to "Desktop_Orig"
I put your copy in there
I connected to the machine and clipboard worked no issues
I disconnected, then copied the original files back in
Connected again, clipboard still works

Idk what on earth is happening but now it works again with the original files in place.
Your modified files never threw any errors either.

**Comment by lucent-sea** [comment]
If there were no errors, then I'm guessing it was something on the browser side.  Did you update your server at some point recently?  Maybe I had broken it in a previous release, then fixed it without realizing it.  And the old file was cached.  🤷

**Comment by Jonathan-Garber** [comment]
Nah, didn't update anything. I tried to tests in a private tab which should
have been no cache/history to work from.
It's weird but it seems to be resolved now.
