### ISSUE TITLE
Availability and Roadmap for 2021

### ISSUE THREAD

**Issue by lucent-sea** [lucent-sea/Remotely#200]
I'm going to be taking a break from Remotely development in 2021.  I really need to spend more time with my family and more time on myself.  And if I have inspiration for another project or something I want to learn, it would be nice to have the bandwidth for it.  There just isn't enough reward in this to justify the amount of time and effort I've been putting in before work, after work, and on weekends.

I've downgraded the public demo server, since the $51/month I've been getting from GitHub Sponsors was barely covering the costs.  I've also begun banning IP addresses of those who are abusing the server.

Issues will continue to get looked at, but I'll probably only act on ones that are critical and have logs included.

Take care, everyone.  Hopefully this year brings all the joy and wellbeing that's sorely needed after this last one.

**Comment by swilkey** [comment]
Jared, thanks again for all the work you have put into this solution and
particularly the significant time you've clearly spent on it recently.
Enjoy your time with family!
Regards
Stephen

**Comment by stevesobol** [comment]
Thank you for your work on this. I'm still planning on working on my customizations, and possibly a Mac port (a port for Intel Macs, anyhow - I very badly want an M1 Mac mini, but I don't have the money to buy one yet). Enjoy your time off!

**Comment by lucent-sea** [comment]
Thank you, @stevesobol and @swilkey. Very much appreciated. :)

**Comment by Fimeg** [comment]
@lucent-sea I apologize for being just a silent observer. You have people talking about this project, a group of 15 different companies. With the worldwide issues with major platforms a lot of us are starting to look toward self-hosted and opensource systems. I'd like to open a dialog with you sometime. 

My company personally is very intrigued by the more recent support from @stevesobol and @swilkey among a few others. We use Zabbix to monitor the myriad of workstations and send scripted responses to mitigate the majority of calls for clients. Remotely has only recently been on the testing field, maybe for around the past 6 months as a viable alternative to major platforms. It encompasses all of my needs. A sister company is thrilled for the Linux support as they work to move it to nodes like Pi, and I'll be honest ARM support is outside of my field and I don't know the first thing they're trying to do. 

Your family must come first, that's the founding statement my company started with. If Remotely.One is not the project you want to continue that's quite fine, but a great deal of us will miss the mind that put this together. It's been quite in-depth and good work. If you feel inclined to continue on this project, perhaps after some respite, Remotely.One is getting refined just enough to have some charitable people invest in you and it's development. My company in particular would invest without a clause of expectancy; it's your creation and you've done well. A sincere thanks.

**Comment by skadefro** [comment]
@lucent-sea just came across this project. **Impressive** work! 
Feel free to reach out if your interested in some kind of corporation.

**Comment by lucent-sea** [comment]
@Fimeg Wow.  Thank you so much for this response.  I'm kind of speechless.  You made my day, though.  :) 

I sincerely appreciate your interest in supporting the project.  As you may have seen echoed in other posts, my biggest obstacle is time.  There's so much I would love to do with Remotely, such branding, Mac support, improved bandwidth usage, a script library, scheduled tasks...  The list goes on and on.  :)

Unfortunately, I simply don't have time to do it while working full time and taking care of my family.  And trying to do it all has led me to exhaustion and burnout more times than I can count, sometimes to a publicly embarrassing degree.

As much as I appreciate the sponsorships I've received so far, it doesn't really help the situation.  It's kind of an all-or-nothing situation.  As long as I still need to work full-time, I don't have time or energy for Remotely.

This is why I've been asking people to donate to a charity instead.  The $50/month I'm receiving now doesn't change my life in the slightest, but it could mean the world to others in need.

And if I'm being completely honest, it's kind of disheartening to see others starting to earn money by supporting/extending Remotely.  I've spent years building the platform, largely for free, and I wish it were me who had time to provide services and benefit from it.  No offense to anyone reading this.  It just stings a little.

I wish I could work on Remotely full time.  I wish I could implement all the features that everyone (and myself) wants, provide support, refine existing stuff, refactor and write more tests, etc.  But it just doesn't seem possible while still needing to work a separate full-time job.

I hope that doesn't sound like too much complaining.  As you can tell, I struggle a lot with this topic.  :)  It's very challenging to have a creative and entrepreneurial spirit, wanting so badly to create something you can live off of, but never being able (or knowing how) to get there.

**Comment by lucent-sea** [comment]
Thank you, @skadefro. :)

**Comment by singularo** [comment]
Thanks @lucent-sea for your work. Enjoy time with family.

**Comment by swilkey** [comment]
> @lucent-sea I apologize for being just a silent observer. You have people talking about this project, a group of 15 different companies. With the worldwide issues with major platforms a lot of us are starting to look toward self-hosted and opensource systems. I'd like to open a dialog with you sometime.
> 
> My company personally is very intrigued by the more recent support from @stevesobol among a few others. We use Zabbix to monitor the myriad of workstations and send scripted responses to mitigate the majority of calls for clients. Remotely has only recently been on the testing field, maybe for around the past 6 months as a viable alternative to major platforms. It encompasses all of my needs. A sister company is thrilled for the Linux support as they work to move it to nodes like Pi, and I'll be honest ARM support is outside of my field and I don't know the first thing they're trying to do.
> 
> Your family must come first, that's the founding statement my company started with. If Remotely.One is not the project you want to continue that's quite fine, but a great deal of us will miss the mind that put this together. It's been quite in-depth and good work. If you feel inclined to continue on this project, perhaps after some respite, Remotely.One is getting refined just enough to have some charitable people invest in you and it's development. My company in particular would invest without a clause of expectancy; it's your creation and you've done well. A sincere thanks.

Fimeg, I appreciate your comments, would it be possible for me to contact you off-list?

**Comment by lincoln131** [comment]
Just to reiterate what others have said, I'm blown away by Remotely. It is practically everything I ever wanted from a self hosted remote assistance platform. 

That said, family first. I appreciate all you've done!

**Comment by sinichi19** [comment]
When the first day saw this post I'm sad because I think another open source great project will not update but understandable because the most important is the family. 

Thank you Sir for all you've done and very appreciated.

More Power and Keep Safe,

God Bless 
Sir Jared

**Comment by MarkIvanowich** [comment]
I just learned about Remotely just over a week ago. I need to say **thank you**!

Regarding others profiting off your hard work;  What about paid upstream access sold through the Translucency/Remotely website? Make profits _before_ the scummy people see it on GitHub. 
Even pay-what-you-like on the Remotely download page would go really far. 

As for working on yourself, I just got out of a depressive rut a few days ago. Please know that you are not alone.
Spending time with family **is the right choice**. 
When times are hard remember **there is nothing wrong with leaning on others for help**.
The individuals in this thread want to see you succeed.

**Comment by lucent-sea** [comment]
Apparently I can't keep away from Remotely.  I keep hoping...  :D

**Comment by ovidiubica** [comment]
You remind me of Max Goodwin ... "How can I help"?
