### ISSUE TITLE
Registration is still disables after changing .json 

### ISSUE THREAD

**Issue by itkujo** [lucent-sea/Remotely#201]
Maybe I am doing it wrong. 
I went to /var/www/remotely/ then used nano to edit appsettings.json to give a -1 value to MaxOrganizationCount. Saved file restarted server, was not able to register new admin with new org. What am I droing wrong? :'(

**Comment by lucent-sea** [comment]
Do you have an `appsettings.Production.json`?  That will override `appsettings.json`.

I'm not able to replicate the issue.  After changing the value and logging out, the Register link is available again.

**Comment by lucent-sea** [comment]
Closing due to no response.
