### ISSUE TITLE
Windows 10 Client crashing with WebRTC enabled

### ISSUE THREAD

**Issue by zerovertex** [lucent-sea/Remotely#204]
I have other Win 10 PCs that aren't having any issues, but I have one that crashes on remote control session. I've tried the latest version 2021.0.04.1928 as well as 2020.11.13 version. The service for the agent remains running but the remote control session crashes and restarts over and over again.

App crashes with this in the Application Event Log

Faulting application name: Remotely_Desktop.exe, version: 2021.1.9.1322, time stamp: 0x5fbf100e
Faulting module name: mrwebrtc.DLL, version: 0.0.0.0, time stamp: 0x5f745f18
Exception code: 0xc0000409
Fault offset: 0x00000000005ba01d
Faulting process id: 0x538
Faulting application start time: 0x01d6e7c634d739f6
Faulting application path: C:\Users\user\AppData\Local\Temp\Remotely_Desktop\Current\Remotely_Desktop.exe
Faulting module path: C:\Users\user\AppData\Local\Temp\Remotely_Desktop\Current\mrwebrtc.DLL
Report Id: 70fff655-c87b-440f-82cf-94306bd01b42
Faulting package full name: 
Faulting package-relative application ID:

Disabled WebRTC in the settings for the system and was able to stay connected with no issues. What would cause WebRTC module to crash on Windows 10 client?

**Comment by lucent-sea** [comment]
The crash is happening in Microsoft's WebRTC library, which I can't fix.  Turning WebRTC off for the device is the only workaround until they fix the library.

**Comment by zerovertex** [comment]
Good to know! Thank you for your hard work, Jared!
