### ISSUE TITLE
Remotely used Port

### ISSUE THREAD

**Issue by sinichi19** [lucent-sea/Remotely#209]
Good Day,

To All,

For additional security, may I request what ports used by remotely  
And if possible to change it.

Like Example:
The Resident Agents installed in devices what ports used to communicate to the server url.

Thank You

**Comment by swilkey** [comment]
Sinichi,

As I understand it, all communication is done over https.  When I 
installed it on my server I didn't open up any ports.  The clients 
contact the server on https and the server responds to the clients over 
that connection.  The server never initiates contact with the clients, 
which is how it is able to work over firewalls etc.  Any client with 
access to the internet to make https connections can establish a 
connection with the server and as Jared mentioned in another post 
recently, that connection is maintained at 5 minute intervals from a 
client where the software is running.  As a result, when you need to 
initiate a remote control session, there is already an active connection 
between the client and the server for the server to then tell the client 
it needs to initiate a remote control session.

I'm not the developer but I'm sure Jared will comment if I've got this 
wrong.

Regards
Stephen
------ Original Message ------

**Comment by sinichi19** [comment]
@swilkey  thank you sir for your comment. I'm not also a developer ^__^ only want to make sure if just incase some attacker or virus use the remotely agent to control/access the computer the additional security is dont use the default port (if have) used by agent to communicate.

But like what your said the agent dont used any port and only communicate via https sound good for me.

Thank You and More power

**Comment by swilkey** [comment]
As an additional comment, what you are talking about is "security by obscurity" and while in days before automated hacking it may have provided a moderate security benefit, realistically now, with tools like https://www.shodan.io/ and automated hacking tools, security by obscurity provides the user with a false sense of security but no real security gains, so it isn't even worth the effort to do.  But as noted, in the case of remotely, it is not applicable anyway.

**Comment by sinichi19** [comment]
@swilkey  thank you sir and more power
