### ISSUE TITLE
Build: Warning Message 

### ISSUE THREAD

**Issue by sinichi19** [lucent-sea/Remotely#212]
Good Day,

To All,

Sorry for this question I'm not a developer and not familiar with this error.
Tried to build from source and successfully created for linux hosting upon building saw this message and dont know if this is normal or I need to adjust or install something to remove the warning message.
![image](https://user-images.githubusercontent.com/44279612/104992814-c4317a00-5a5c-11eb-97ab-5be6407039ad.png)

But after the second run of the command to build there is no warning message like picture above only encountered when 1st downloaded the source code and build.

Thank You and More power

**Comment by lucent-sea** [comment]
They're just attributes on that have been marked obsolete because they use a feature that isn't supported in .NET 5.  You can safely ignore this.  Remotely isn't even using them.  I'll remove the attributes later.

**Comment by sinichi19** [comment]
> They're just attributes on that have been marked obsolete because they use a feature that isn't supported in .NET 5. You can safely ignore this. Remotely isn't even using them. I'll remove the attributes later.

thank you sir, more power and keep safe.
