### ISSUE TITLE
ID changes constantly !!

### ISSUE THREAD

**Issue by LucianoCM7** [lucent-sea/Remotely#216]
Friend,

The office for windows changes the 9-digit ID every 1:03 minutes and remote sessions drop and you need to reconnect with a new ID, plus every connection made after 1:03 minutes goes down again.

[Erro Remotely.docx](https://github.com/lucent-sea/Remotely/files/5861274/Erro.Remotely.docx)

**Comment by LucianoCM7** [comment]
Is the most current repository to be used in the installation process the one below?

wget https://github.com/lucent-sea/Remotely/releases/download/v2020.05.13.1949/Remotely_Server_Install.sh

**Comment by lucent-sea** [comment]
The latest release is the one at the top that says "Latest release": https://github.com/lucent-sea/Remotely/releases

As I said in my reply to you're email, you'll need to look at the logs.  The connection is breaking, likely due to unstable internet or an incorrectly-configured reverse proxy.

I have two servers running the latest release with no issues with remote connections.

**Comment by LucianoCM7** [comment]
Friend, again sorry for the time, but there was this error at the end ...
where am I missing?

root@remoto:~# wget
https://github.com/lucent-sea/Remotely/releases/download/v2021.01.22.0533/Remotely_Server_Install.sh
--2021-01-25 02:32:29--
https://github.com/lucent-sea/Remotely/releases/download/v2021.01.22.0533/Remotely_Server_Install.sh
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-01-25 02:32:30 ERROR 404: Not Found.

Em dom., 24 de jan. de 2021 às 15:21, Jared <notifications@github.com>
escreveu:

**Comment by LucianoCM7** [comment]
![Log_Servidor](https://user-images.githubusercontent.com/75502974/105661535-63ff6580-5eac-11eb-84be-a5374052db78.PNG)

But the number of my organization is not the one that appears on the print ... my organization on the panel is: d81e65cd-ea32-459e-a03f-53d44b929ab8

**Comment by LucianoCM7** [comment]
friend I decided here ... was the cache of browsers.

Another thing this site https://www.hover.com/ is at all times delete my domain and will already be the 3 payment I make for them ... you indicate me another reliable?

**Comment by LucianoCM7** [comment]
friend I managed here ... was the cache of browsers.
Another thing this site https://www.hover.com/ at all times deletes my domain and will already be the 3 payment I make for them ... Do you give me another reliable one?

**Comment by lucent-sea** [comment]
I'm glad you figured it out.  :)

I highly recommend https://www.namecheap.com/ for domain names.

For VPS servers, https://www.vultr.com/ and https://www.digitalocean.com/ are both really good platforms.
