### ISSUE TITLE
how to change the footer after the app is installed on to the ubuntu server

### ISSUE THREAD

**Issue by rhinopctec** [lucent-sea/Remotely#218]
how to change the footer after the app is installed on to the ubuntu server

**Comment by sinichi19** [comment]
you need to build your own ubuntu hosting server. to change from the root and hardcoded the url etc. using visual studio 
https://github.com/lucent-sea/Remotely

**Comment by rhinopctec** [comment]
I'm totally lost how to do the build on Github or even locally I've been at it for a week now,  do you have any tips or step by step to follow for a noob or beginner?

**Comment by sinichi19** [comment]
Im not also a developer and only followed what in documentation 
![image](https://user-images.githubusercontent.com/44279612/105946823-f10c0f80-60a2-11eb-9316-e698f69bdd70.png)

**Comment by rhinopctec** [comment]
I did all this but still wont build m missing something

**Comment by lucent-sea** [comment]
It's impossible to say without logs or error messages.
