### ISSUE TITLE
Block Remote input with error.

### ISSUE THREAD

**Issue by LucianoCM7** [lucent-sea/Remotely#219]
Friend ... 

when trying to block by the "Block Remote input" button I noticed that only the user cannot write in a notepad or word for example ... the screen is not locked for the user ... the user can move windows etc ... he does everything but write !! Do you have any configuration, because I used the same installation url that is in the video?

**Comment by LucianoCM7** [comment]
and the function "Ctrl + Alt + Del" when I click on it a message appears: "Not available for this session".

**Comment by sinichi19** [comment]
> Friend ...
> 
> when trying to block by the "Block Remote input" button I noticed that only the user cannot write in a notepad or word for example ... the screen is not locked for the user ... the user can move windows etc ... he does everything but write !! Do you have any configuration, because I used the same installation url that is in the video?

If im not mistaken thats work properly input device only block like keyboard and mouse, the screen or display is output device.

**Comment by LucianoCM7** [comment]
I will use this idea of remote access in my company due to Covid-19 and
this option was legal, as there are users who keep moving the mouse and
keyboard when it comes to support by the Help Desk.

Em ter., 26 de jan. de 2021 às 22:11, Sinichi <notifications@github.com>
escreveu:

**Comment by lucent-sea** [comment]
Ctrl + Alt + Del is only available when Remotely is installed as an unattended service.  Invoking it requires service-level permissions.  It can't be done from a UI app running in the user's session, even if run as administrator.

I wasn't able to replicate the block input issue.  It works fine for me.  It could be related to regional/language settings.

Regardless, all I'm doing is calling the native Windows function [BlockInput](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-blockinput).  If it's not working, I'm afraid there isn't anything I can do to fix it.

**Comment by LucianoCM7** [comment]
Friend, good morning!! I

I managed to solve the button problem here ... I tested it on the Chromiun
browser and the button worked ... thanks for the help !!

know I'm asking for too much and I apologize for that !! I have a question
if the words that appear on the site with animation in "Flash" ("Remotely
desktop" and "Remotely Scripting") can be changed or changed ... is there a
* .html or * .index file in the code?

Em qua., 27 de jan. de 2021 às 22:22, Jared <notifications@github.com>
escreveu:

**Comment by LucianoCM7** [comment]
Friend, good night ...

it's not much because the dollar is high here in Brazil, but I had promised
in the email that I will make a deposit ... I believe that next week I will
make another deposit for you !!

Friend ... I'm trying to add my card and paypal is not accepting ... I'll
see if I put a value in there I saw a payment slip to have credit to send
to your Paypal account.

Em sex., 29 de jan. de 2021 às 09:30, luciano menezes <cimcorp2018@gmail.com>
escreveu:

**Comment by LucianoCM7** [comment]
Friend, good afternoon ...

Follow a value to your account for the Remotely project ... thanks !!

Em sex., 29 de jan. de 2021 às 20:41, luciano menezes <cimcorp2018@gmail.com>
escreveu:

**Comment by LucianoCM7** [comment]
Friend, good night ...

you can assemble a custom source code ... how much is the dollar value?

Em seg., 1 de fev. de 2021 às 14:48, luciano menezes <cimcorp2018@gmail.com>
escreveu:

**Comment by lucent-sea** [comment]
I'm sorry, but I'm not doing customizations right now.
