### ISSUE TITLE
how do I build and deploy Remotely on Github once I've Replaced the needed Files

### ISSUE THREAD

**Issue by rhinopctec** [lucent-sea/Remotely#221]
I really need help am new to all this how do I build and deploy Remotely on Github once I've Replaced the needed Files to create the Ubuntu_Server_Install and other files I've read the Documentation front to back for a week now and still cant understand how to build or deploy Remotely.

**Comment by lucent-sea** [comment]
Building, deploying, and hosting Remotely is the same as any other ASP.NET Core app.  It's complicated for people who are new to the process, but I can't really help with that.  It is what it is.

The documentation can be found on Microsoft Docs:  https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0
