### ISSUE TITLE
Remotely from Master 

### ISSUE THREAD

**Issue by sinichi19** [lucent-sea/Remotely#227]
Good Day,

To All,

If there is using or update their server using the master and not the released package.
May we know the performance and if its ok to use?

Sorry little bit confuse if I use the last released version or may I used the source code from the master branch.

Thank You and More Power.

**Comment by lucent-sea** [comment]
Yeah, it's okay to build and deploy from master.  The public server at https://app.remotely.one is always running Master.  I try to keep it in a working state.
