### ISSUE TITLE
Device can't get removed

### ISSUE THREAD

**Issue by dennyb** [lucent-sea/Remotely#228]
Hey there,
I'm trying remotely just a few days but I guess I found a little "error".
Is it true, that there is no option to delete a device? I couldn't find any option, not under "actions" nor in the edit tab of this device.

**Comment by swilkey** [comment]
Hi Denny, welcome to the community!

Please see this link for the answer: https://github.com/lucent-sea/Remotely/issues/31

**Comment by dennyb** [comment]
Thanks!
This helped.
