### ISSUE TITLE
Git Clone Question

### ISSUE THREAD

**Issue by sinichi19** [lucent-sea/Remotely#233]
To All,

Good Day,

Its possible to git clone the older version to get the exact version when build for linux hosting.

only can git clone is from the master branch.

cant build new hosting when downloaded the source code direct to release.

--

my workaround is git clone from the master branch then replace the source code from older release. but when I build for linux hosting the remotely version is not the same where I downloaded the source code.

**Comment by stevesobol** [comment]
@sinichi19 for what it's worth, I'm doing some customizations for my own use, and I never use the latest and greatest. I pick the most recent release and work from that.
