### ISSUE TITLE
Remotely Instant Support Clients - Ubuntu Executable

### ISSUE THREAD

**Issue by waynem-bris** [lucent-sea/Remotely#237]
I have remotely installed on Ubuntu 18.04 x64.

When I download the client (Ubuntu Executable) and tick the "execute" permission, I get a popup (see the attached image).

My desktop is running Ubunti 20.04

![Remotely](https://user-images.githubusercontent.com/60527104/107583803-2f7b0000-6c47-11eb-8bdb-c46fb4f315d5.png)

**Comment by lucent-sea** [comment]
I think this is a bug with .NET 5.  Regardless, it would normally just say you need to run it with sudo.  So yeah, please run it from the terminal with sudo.
