### ISSUE TITLE
1 Click Remove all notifications

### ISSUE THREAD

**Issue by opensource008** [lucent-sea/Remotely#247]
Good Day,

To All,

![image](https://user-images.githubusercontent.com/78790472/111130567-5617b800-85b2-11eb-91b3-0bc4ce31b280.png)

Requesting for your kind assistance

Dont know if there is workaround or other way to read all or remove all notifications

Thank You and More power

**Comment by lucent-sea** [comment]
I added a Clear All button.

![image](https://user-images.githubusercontent.com/20995508/111533194-bf6b0880-8723-11eb-9c7c-ece563d4eb63.png)

**Comment by opensource008** [comment]
Wow than you very much Sir
