### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by ovidiubica** [lucent-sea/Remotely#250]
Thank you for the best opensource self hosted remote solution out there. Is there any way I could modify the session time limit?

![image](https://user-images.githubusercontent.com/4251997/111784195-c7fa4500-88c3-11eb-9df5-88e28752fde2.png)

**Comment by lucent-sea** [comment]
There's no time limit.  That message means there was a network interruption, and the websocket connection was lost.  It could also be the result of a reverse proxy misconfiguration.

**Comment by ovidiubica** [comment]
This seems to be [related to SignalR](https://github.com/SignalR/SignalR/issues/4536) and latest Chromium >88.
The disconnect happens after ~minutes of chrome tab inactivity.
