### ISSUE TITLE
Official OCI Image for Linux

### ISSUE THREAD

**Issue by malimach** [lucent-sea/Remotely#255]
Remotely seems like a very cool project and I would love to try it out, but all the applications on the server I'm managing are distributed as container images (on e.g. Docker Hub) so that they can be run by a container runtime (e.g. Docker Engine, podman). I noticed that there are unofficial images on Docker Hub but running untrusted images is a major security concern. The image can be built using a [GitHub Action](https://github.com/docker/build-push-action). I understand if it would be too large of a maintenance burden, but I would appreciate at least keeping the [issue](https://github.com/lucent-sea/Remotely/issues/60) open, as others might be interested in this as well.

**Comment by lucent-sea** [comment]
I'm currently working on a cross-platform CLI tool that integrates with GitHub's REST API to build and install the server.  There are more pressing tasks at the moment (Mac agent and video encoding), but I might be able to look into this down the road.

If someone wants to take a stab at adding a Actions workflow for this and integrating it with the new server installer CLI tool, that would be cool too!

**Comment by lucent-sea** [comment]
I've got a Docker image building and deploying from Azure DevOps now:  https://hub.docker.com/repository/docker/translucency/remotely

**Comment by malimach** [comment]
Awesome! Can't wait to give it a try.
