### ISSUE TITLE
100% Usage

### ISSUE THREAD

**Issue by opensource008** [lucent-sea/Remotely#256]
Experienced 100% memory and CPU usage

When you access the  website or try to remote you will noticed the slow response of the server then when you monitor the CPU and Memory usage are 100% 

**Server Details:**
Ubuntu 18.04
 6gb memory
4core i3 CPU

400 Devices (Agents installed)

----
To All,

May I request Hardware recommendation?

Before, Sir Jared said for 5k devices would require about 1GB on Linux. But I have only 400 and then my memory usage is 100%
When I monitor using top command on terminal saw the www-data / dotnet using more resources.

And if there is workaround or tweak to minimize the memory usage.

Thank you and more power

**Comment by bmcgonag** [comment]
Have to ask what you have 400 devices for?  I suppose this is a work environment of some sort.  Just curious.

I run remotely on a 1GB RAM VPS with about 10 devices, and it doesn't even start to push it, but that's nowhere near 400 or 5000.

**Comment by lucent-sea** [comment]
That's definitely abnormal.  The below VM hosts two Remotely servers with a total of 70-120 devices connected, depending on the time of day.  It never goes above 10% CPU and 55% memory.

Are you getting DoSed?  Have you checked the Nginx logs?  Have you checked the Remotely server logs to see if anything strange is happening (errors, tons of auth failures, etc.)?  Do you have any automated scripts that make API requests (e.g. alerts) that might be misbehaving and overloading the server?

![image](https://user-images.githubusercontent.com/20995508/112737824-a5e37100-8f1a-11eb-8b6c-f74a50e76787.png)

**Comment by lucent-sea** [comment]
FYI, regarding the DoS thing, I highly recommend using IPBan:  https://github.com/DigitalRuby/IPBan

**Comment by opensource008** [comment]
Thank you for your reply Sir @lucent-sea 
Will check the nginx logs tomorrow and remotely.

*Installed ssh but local only and allow only my ip.

*For remotely logs think there is 20 agent trying to connect but because i changed database before and not update the agent on devices only saw the logs of 20 devices trying to connect. will check others

*Your picture have 2gb memory and have 70 to 120 devices and getting 50% memory, think system used lots of memory.. like you said before for the 5k devices only need is 1gb of memory for linux

**Comment by lucent-sea** [comment]
My estimate of 1GB for 5k is for the connections themselves. There's overhead for rest of the dotnet process and everything else that's running. If I had 0 active connections, I wouldn't be at 0 memory use. 

I still think the estimate should be pretty accurate in most conditions. I've had over 4k concurrent connections on a fork of Remotely, and the total memory use for the whole OS was a little over 2GB.

However, there was a memory usage issue during the agent update process on an older version of Remotely, but it's been fixed for quite a while.

**Comment by opensource008** [comment]
> My estimate of 1GB for 5k is for the connections themselves. There's overhead for rest of the dotnet process and everything else that's running. If I had 0 active connections, I wouldn't be at 0 memory use.
> 
> I still think the estimate should be pretty accurate in most conditions. I've had over 4k concurrent connections on a fork of Remotely, and the total memory use for the whole OS was a little over 2GB.
> 
> However, there was a memory usage issue during the agent update process on an older version of Remotely, but it's been fixed for quite a while.

-----
For now not suspecting Dosed ,, think there is something in dotnet running in the server as per my personal observation,, 

Will try to migrate the server using ubuntu 20.04 and monitor the performance.

**Comment by lucent-sea** [comment]
What version of Remotely are you running?

There shouldn't be any problem handling 400 connections with 6GB and a quad core. Something abnormal is definitely happening.

**Comment by opensource008** [comment]
> What version of Remotely are you running?
> 
> There shouldn't be any problem handling 400 connections with 6GB and a quad core. Something abnormal is definitely happening.

---
1st experienced is the version from January or February 2021..
then i think there is only a problem from that version so did is to git clone from your repo yesterday but still encountered the problem.

**Comment by opensource008** [comment]
Hoping there is server also have lots of active or online devices to check the system is ready for large number of computers.. like thousands of computers

**Comment by opensource008** [comment]
To All,
I'm not a developer, but if there is a way or need to add code before I build remotely for linux hosting to reduce or limit the dotnet memory usage for server.

Thank you

**Comment by lucent-sea** [comment]
I created 500 connections to my server with the load tester (plus the 100 on the other Remotely instance), and it didn't have any issues.

If you had a lot of devices dropping and reconnecting, that could cause high resource use.

![image](https://user-images.githubusercontent.com/20995508/112761346-c14c8b80-8faf-11eb-8798-f821d699d59f.png)
![image](https://user-images.githubusercontent.com/20995508/112761350-c6113f80-8faf-11eb-857f-981cc045e785.png)

**Comment by opensource008** [comment]
> I created 500 connections to my server with the load tester (plus the 100 on the other Remotely instance), and it didn't have any issues.
> 
> If you had a lot of devices dropping and reconnecting, that could cause high resource use.
> 
> ![image](https://user-images.githubusercontent.com/20995508/112761346-c14c8b80-8faf-11eb-8798-f821d699d59f.png)
> ![image](https://user-images.githubusercontent.com/20995508/112761350-c6113f80-8faf-11eb-857f-981cc045e785.png)

-------
After migrated to Ubuntu 20.04 works ok now, the memory stable to 40 to 45% 
Will monitor this.

Greatly appreciated the your prompt actions and testing you did.

Thank You very much

**Comment by lucent-sea** [comment]
Glad to hear things are stable now.  Thanks for the update.  :)
