### ISSUE TITLE
Login loop when using Microsoft Edge.

### ISSUE THREAD

**Issue by johnvkampen** [lucent-sea/Remotely#267]
Remotely version 1.0.0.0
Running in docker container (https://hub.docker.com/r/virusbrain/remotelyserver) with a nginx ssl proxy in front.
MS Edge version 89.0.774.75 (Official build) (64-bit)

After entering my credentials and clicking the login button the page redirects to the main home screen without logging in. I've tried another machine with MS Edge but the behaviour is the same. 

Other browsers I've tried (firefox on windows 10 and samsung browser on android) have no issues. Will provide more info if needed.

\edit: I double checked the docker hub page and it turns out that the :latest tag is actually a year old and that there was a tag for the actual latest release. I've changed my compose file to use that tag and now MS Edge is working as intended.

**Comment by lucent-sea** [comment]
Thanks for the feedback.

Please understand that this is only a hobby project that I work on in my free time.  As such, I don't have available time to provide support with issues regarding hosting environments that aren't related to the code itself.  This is particularly true when using a hosting method other than what's described in the readme.

There's currently [a discussion on Reddit ](https://www.reddit.com/r/remotely_app/comments/mnfhtn/login_loop/) about the same Docker container.  I would try connecting with other users there.  :)
