### ISSUE TITLE
Remotely_Server_Installer error: GitHub API call to trigger build action failed

### ISSUE THREAD

**Issue by Basti-Fantasti** [lucent-sea/Remotely#274]
**Describe the bug**

Problem automatically appears after giving all options to the installer

**To Reproduce**
1. run ./Remotely_Server_Installer as root
2. enter all needed details (see screenshot)
3. perform server install

**Remotely Version**
Server: Latest (2021.04.13.2004)

**Expected Behavior**
Installation takes place

**Screenshots**

![remotely_error](https://user-images.githubusercontent.com/1663072/114682934-da736d00-9d0f-11eb-8b3c-681678f2e56b.png)

**Additional Context**
- Github access token is newly created with full repo privileges selected
- original Remotely repo was forked
- A prior installation was done on the same server using the Ubuntu installer executable but removed

**Comment by demirozmustafa** [comment]
hello i have same problem.

**Comment by lucent-sea** [comment]
Hmm.  It looks like accounts that haven't used Actions before need to go into Actions tab and explicitly enable it.  (Screenshot below.)  Is that the case on your account?  Does it work after enabling it?

If so, I'll add it to the docs!

![image](https://user-images.githubusercontent.com/20995508/114711630-0bd64380-9ce4-11eb-9db8-6d653ae95988.png)

**Comment by Basti-Fantasti** [comment]
Hi and thanks for the quick reply

Now it starts building.

Here's the updated log:

``````
Performing server install.  GitHub User: Basti-Fantasti.
Server URL: https://remotely.gtr.de/.  Installation
Directory: /var/www/remotely/

Get artifacts response status code: OK

Trigger GitHub Actions build.

Dispatch response status code: NoContent

Build action triggered successfully.  Waiting for build
completion.

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK


``````

I'm waiting for the whole process to be finished and keep you updated 👍

**Comment by lucent-sea** [comment]
Thanks so much for the detailed reports!  I appreciate it.  :)

**Comment by ovidiubica** [comment]
I tried the Github build action last weekend and used to  fail before decoding the pfx.  The if condition would not pass. I'm not sure if it was a bug or I needed to set up a new Personal Access Token which may be required for the workflow to sign the certificate. I removed the condition and build finished properly after ~ 10 minutes.

**Comment by ovidiubica** [comment]
It still fails for me, what am I missing? Trying to build for linux.
Run if (!($env:PfxBase64)) {
Skipping cert signing because Base64_Encoded_Pfx secret is missing

Remove-Item: D:\a\_temp\482a6fbf-4a89-4654-a530-331b5b19c992.ps1:2
Line |
   2 |  Remove-Item -path "$env:GITHUB_WORKSPACE\GitHubActionsWorkflow.pfx"
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'D:\a\Remotely\Remotely\GitHubActionsWorkflow.pfx' because it does not exist.

Error: Process completed with exit code 1.

**Comment by lucent-sea** [comment]
Just pushed an update to the build workflow.  I hadn't run this without all the secrets set up.  Can you try again?

**Comment by ovidiubica** [comment]
Sure, I'll let you know.

**Comment by ovidiubica** [comment]
Perfect, build is green now. Thanks Jared.

**Comment by lucent-sea** [comment]
Awesome!  Thank you too.  :)   This was a major issue for the new build process, and you helped me find it quickly.  Much appreciated.
