### ISSUE TITLE
Remotely_Server_Installer -r parameter assigned two times

### ISSUE THREAD

**Issue by Basti-Fantasti** [lucent-sea/Remotely#275]
**Describe the bug**
When calling the Remote_Server_Installer the **-r** property is used twice.
* --reference -r
* --reverse-proxy -r

**To Reproduce**

run ./Remotely_Server_Installer --help
check log details as well as Example stated at the end of the help message

**Remotely Version**
Server: 2021.04.13.2004

**Expected Behavior**

Seperate identifiers for each option

**Additional Context**

I'm not sure if this is a bug or if this is intended to be like this.  
I stumbled upon this when trying to use the installer.

**Comment by lucent-sea** [comment]
Doh!

Thanks for pointing this out.  I've changed "--reverse-proxy, -r" to "--web-server, -w".   I think this makes more sense since the web server running Remotely is capable of more than just reverse proxy.  And IIS isn't a reverse proxy at all.
