### ISSUE TITLE
Example_Nginx_Config.txt

### ISSUE THREAD

**Issue by opensource008** [lucent-sea/Remotely#279]
Good Day,

Sir looking only for your official Example_Nginx_Config.txt to try your pre-released
Cant find in Utilities folder,

Thank You and More power

**Comment by Basti-Fantasti** [comment]
Yes, the file seems to be gone

**Comment by lucent-sea** [comment]
It's back in there now.

I also added Nginx configurations to the installer.  :) 

![image](https://user-images.githubusercontent.com/20995508/115028845-2f32f700-9e7a-11eb-8412-b5623721009e.png)
