### ISSUE TITLE
Remotely_Server_Installer invalid shell script for NGINX Ubuntu build

### ISSUE THREAD

**Issue by Basti-Fantasti** [lucent-sea/Remotely#280]
**Describe the bug**
After a successful build process, the artifacts are downloaded and extracted ok.
The **/tmp/sh** file used for local installation is malformed. 

![2021-04-15 09_41_52-Window](https://user-images.githubusercontent.com/1663072/114833319-be370500-9dcf-11eb-8e9b-dabd379ca0e5.png)

The shebang is indented and the line end is set to CR LF which causes the bash not to be executed even if the shebang is corrected.

The upcoming error message:

````
root@remotely:/tmp# ./sh
-bash: ./sh: /bin/bash^M: bad interpreter: No such file or directory

````

**To Reproduce**
1. Build the project using NGINX on Ubuntu
2. Wait for the artifacts to be download and extracted
3. Wait for the attempt to start the **sh** file from within the installer

**Remotely Version**
Server: latest

**Expected Behavior**
Flawless execution of installation 😄 

**Additional Context**

I temporarily solved the two issues for me by removing the leading spaces in the first row and converting the line ends to LF only using the following command:

````
 sed -i -e 's/\r$//' /tmp/sh
````

Update:

After fixing the issues stated in this bug report the installation is now basically working and I'm starting to set it up.

**Comment by Basti-Fantasti** [comment]
thanks 😄

**Comment by lucent-sea** [comment]
Out of curiosity, is this your first time using Remotely?  If so, I applaud your perseverance!  Sorry your first experience is during such an unstable period.

**Comment by lucent-sea** [comment]
Bah.  It was saving it with UTF8-BOM too instead of UTF8.  It annoys me how Visual Studio picks a random encoding every time I create or move a shell script. (End of rant)

**Comment by Basti-Fantasti** [comment]
Hi, yes it's my first time trying remotely. 
I read about it in a German security blog. It was mentioned as an open source alternative to AnyDesk or TeamViewer.
It sounded interesting to my so I decided to test it.

And don't worry about the current version. You tagged it "pre-release" so all good 👍 

I'm glad I can help to improve your awesome piece of software!

Best regards
Bastian

**Comment by lucent-sea** [comment]
A published a new pre-release version. This should be fixed.

**Comment by Basti-Fantasti** [comment]
Issue is fixed in latest build.
