### ISSUE TITLE
Missing packages on installation of self built Server on Ubuntu

### ISSUE THREAD

**Issue by Basti-Fantasti** [lucent-sea/Remotely#282]
**Describe the bug**

I've tried to install the server using the supplied Remotely_Server_Install script. 
After downloading the built artifacts and executing the **/tmp/sh** file some basic dependencies were missing in my freshly setup Ubuntu 20.04 LXC Container

I manually had to add
- curl
- software-properties-common
- gnupg

otherwise the installation failed when it tried to add the Microsoft repo via curl.

**To Reproduce**
1. Setup new Ubuntu
2. Build Remotely
3. Wait for sh script to be executed

**Remotely Version**
Server: Version: 2021.04.14.1320
Agent: N/A

**Expected Behavior**
The sh script should make sure that these dependencies are met or these should be added to the documentation so that the person installing the software can manually ensure that the packages are installed

**Comment by lucent-sea** [comment]
I added these to the script. Thanks. :)  Could you run again and confirm?

**Comment by Basti-Fantasti** [comment]
with the latest build it works!
