### ISSUE TITLE
Enhancement: Remember Name in "Remote Session" Start Screen

### ISSUE THREAD

**Issue by Basti-Fantasti** [lucent-sea/Remotely#285]
It would be great to use the provided name of a logged in user for the **Your Name** field on the Remote Session start screen instead of having to type it in every time a remote session is started.

![2021-04-16 14_47_09-Remotely Remote Control](https://user-images.githubusercontent.com/1663072/115026536-e6536080-9ec2-11eb-8ff4-c7c2de71d27c.png)

**Comment by lucent-sea** [comment]
Great suggestion.  Done.  :) e605f174a7b7e9fe1a77841fd52814bd96888733

It will default to your Display Name if you're logged in and created one.

Otherwise, it will populate with the last-used name, which it persists in localStorage.

**Comment by Basti-Fantasti** [comment]
wow that was quick ;-)
what's the suggested way to update?
Sync my github fork with yours and rebuild it over the existing installation?

**Comment by lucent-sea** [comment]
For now, yeah, I'd recommend that.  I recently changed the `Build` workflow to check out from my repo.  So once you update your fork, you won't have to keep updating it.  The installer will pull from my repo with each build.

Once everything's stable and a full release is published, then you can start using release tags in the installer.

Some day, I might adopt a real versioning system.

**Comment by Basti-Fantasti** [comment]
Sounds good. I'll try that and keep you updated

**Comment by Basti-Fantasti** [comment]
Update is done. You're changes are working as expected. 
Name of logged in Person is now added automatically to the "Your Name" field.

Thanks for adding this small change!
