### ISSUE TITLE
Remotely Fails to send FQDN during HELO

### ISSUE THREAD

**Issue by Drehmini** [lucent-sea/Remotely#291]
**Describe the bug**
When using SMTP, Remotely does not send the FQDN to the smtp server during HELO.

**To Reproduce**
0. Use a server that requires FQDN sent during HELO.
1. Configure SMTP
2. Test Config

**Remotely Version**
Server (can be found on about page): 2021.03.25.2059

**Expected Behavior**
Remotely should send FQDN during HELO

**Additional Context**
Here's an snippet of the log:
```
Command parameter not implemented. The server response was: 5.5.2 <756304a12d17>: Helo command rejected: need fully-qualified hostname

System.Net.Mail | at System.Net.Mail.RecipientCommand.CheckResponse(SmtpStatusCode statusCode, String response) at System.Net.Mail.SmtpTransport.SendMail(MailAddress sender, MailAddressCollection recipients, String deliveryNotify, Boolean allowUnicode, SmtpFailedRecipientException& exception) at System.Net.Mail.SmtpClient.Send(MailMessage message) at Remotely.Server.Services.EmailSenderEx.SendEmailAsync(String email, String replyTo, String subject, String htmlMessage, String organizationID) in D:\a\1\s\Server\Services\EmailSender.cs:line 49
```

I think really, this is because Remotely uses [SMTPClient](https://github.com/lucent-sea/Remotely/blob/131ec4f789bcf7ce1941991d22cda51fc57f3c28/Server/Services/EmailSender.cs#L30). [Microsoft recommends not using SMTPClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=net-5.0#remarks).

**Comment by lucent-sea** [comment]
I'll replace it with MailKit.

**Comment by Drehmini** [comment]
Ill go ahead and close the issue and test it once the docker image is updated.

References: d9f81f4ebaa139e0c6ade7d1ebfa9f72c88e52d1 and a59d86b25ca4d0db3eb7415a3be636365477314f
