### ISSUE TITLE
Can I open this app via Webbrowser ?

### ISSUE THREAD

**Issue by Peace569** [lucent-sea/Remotely#293]
I want to know whether I can open this app on webbrowser or not.
In a word, can I control desktop on webbrowser or not using this app ?

**Comment by opensource008** [comment]
yes, remotely is a web-base remote application. and its awesome 👌

**Comment by Peace569** [comment]
Ok, thanks for your reply opensource008.
Then would you teach me how to build this project and open it on the web?
Regards

**Comment by Basti-Fantasti** [comment]
it's all well documented in the main readme file 😉 
You need to have an Ubuntu or Windows system up and running to install the Remotely server.

When that's all done you can connect via your browser to your own server and start from there.

**Comment by Peace569** [comment]
@Basti-Fantasti, I will try readme file in detail again.
I will appreciate it if you will be with me ongoing.

**Comment by opensource008** [comment]
> @Basti-Fantasti, I will try readme file in detail again.
> I will appreciate it if you will be with me ongoing.

important is you have basic knowledge how to use or manage web server like nginx for ubuntu or iis for windows. remotely installations is easy using the script. provided on documentation. 

Like me just read and read 😍🥰

**Comment by Peace569** [comment]
I have a windows server, but It is not sure how to deploy this.
If anyone helps me, I will appreciate it.
You can connect via teamview.
Regards

**Comment by Basti-Fantasti** [comment]
I have not tried the deployment on Windows 😅
I only deployed it on an Ubuntu machine. 

Btw you can also use the [public server](https://app.remotely.one/) available when you don't need a customization.
This should also work out of the box.

Best regards
Bastian

**Comment by Peace569** [comment]
I ran my server on my local.
but I can't know how to share my screen.
https://prnt.sc/11sbv1h
What is this session ID?
How to share my desktop?
How to connect this server on the client?

**Comment by Basti-Fantasti** [comment]
Session Id is generated using the client which connects to your server to request support

The clients can be downloaded on the download page of your server ui

**Comment by sinichi19** [comment]
> I ran my server on my local.
> but I can't know how to share my screen.
> https://prnt.sc/11sbv1h
> What is this session ID?
> How to share my desktop?
> How to connect and control this local server on another client?

First if you familiar using Teamviewer or other remote app you need to an agent or clients installed to the computer want to remote.
If you can notice in your Download page you can see the Portable Instant Support or the Resident Agents that you need to install.
The two are the clients or agent that talk or connect to your server thats your door to enter to the computer.
You need a working server first and run either of the two then the server will generate session ID to your client

**Comment by Peace569** [comment]
What is the role of Agent?

**Comment by sinichi19** [comment]
> What is the role of Agent?

already told you on my post. basically that's your door, that the simple way to describe that. more complicated if you using IT terms.

**Comment by Peace569** [comment]
Thank you,@sinichi19.
Sorry,but I have one question more.
I know how to publish ASP.net core project on the server.(such as Godday)
But I don't know how to deploy on Window server.
I will appreciate it if you let me know.
I am using Windows 10 Enterprise LTSC 2019.
Regards

**Comment by sinichi19** [comment]
> Thank you,@sinichi19.
> Sorry,but I have one question more.
> I know how to publish ASP.net core project on the server.(such as Godday)
> But I don't know how to deploy on Window server.
> I will appreciate it if you let me know.
> I am using Windows 10 Enterprise LTSC 2019.
> In this server, there is not wwwrot folder.
> Regards

I have only basic knowledge using IIS for Windows and my remotely run on Ubuntu for me much easy to install and manage the server.

**Comment by Peace569** [comment]
@sinichi19, thanks for your message.

**Comment by sinichi19** [comment]
> @sinichi19, thanks for your message.
> And Have a good day.

Hopping you can find here more skilled to help you can also try to visit the reddit page of the developer and hopefully you can find one.

**Comment by Peace569** [comment]
@sinichi19 , thanks again.
But I didn't find the solution yet.
I am finding someone who helps me.
