### ISSUE TITLE
Enhancement: Get E-Mail when a customer requests support

### ISSUE THREAD

**Issue by ToLaTE4u** [lucent-sea/Remotely#295]
Hey there! It would be great if you get a notification E-Mail, when someone requests support. Since you may not have the remotely website on focus on the PC to have a view on the bell.
![2021-04-20 14_37_58-Remotely](https://user-images.githubusercontent.com/82883557/115397190-1f067900-a1e6-11eb-82be-0d49ea23ed0d.png)

**Comment by opensource008** [comment]
ticketing system is the key

**Comment by lucent-sea** [comment]
Done!  :)  I'll leave this open until it's officially released.

**Comment by opensource008** [comment]
> Done! :) I'll leave this open until it's officially released.
Nice Sir but,
I'm assuming also have option to disable the email notification if someone request support.

Thank you and more power

**Comment by Delikt** [comment]
> ticketing system is the key ,, i think,,?
Remotely + zammad (https://zammad.org/)

Imagine full integration . ..mhh

**Comment by Delikt** [comment]
Btw.. i got an E-Mail after i tested the "request support" Shortcut - issue is closed?

**Comment by ToLaTE4u** [comment]
@Delikt Yes he implemented it after my request. But as he said he will leave this request open until he has officially released it...

**Comment by lucent-sea** [comment]
I apologize for the delay.  I was on vacation, and work has been crazy since I got back.

Yeah, I did release it.  There's no option to disable it yet, though.  I think there's a lot more thought/work that needs to go into it around who should receive the emails by default, user preferences, notification settings, etc.
