### ISSUE TITLE
After the major overhaul of Remotely

### ISSUE THREAD

**Issue by sinichi19** [lucent-sea/Remotely#299]
Good Day,

Awesome improvement Sir for Remotely new UI is nice and beautiful.

My question Sir is if I still use the old way to build Remotely using windows Like Git clone to your master repo and use the powershell command ( powershell -f publish.ps1 - rid linux-x64 D:\output-path -hostname https://example.com)

Thank You and More power

**Comment by lucent-sea** [comment]
Hello!  

Yes, that still works the same.  :)  In fact, I still use that script as part of my build and deploy process, so it's tested daily.

**Comment by sinichi19** [comment]
Sweet, Thank you and More Power SIR @lucent-sea
