### ISSUE TITLE
Deployment Bug on Windows Enterprise LTS 2019

### ISSUE THREAD

**Issue by Peace569** [lucent-sea/Remotely#301]
Hello everyone.
I am going to deploy the Server project (in Remotely solution) on my Windows server.
But I am getting this kind of error on the Windows server.
https://prnt.sc/11udwiw
There is no error in my local building.
And I followed these steps.
1. I published the "Server" project as folder publish mode and got "publish" folder.
2. I copied all files and folders in "publish" folder, then copied it in the Windows server's folder (C:\\interpub\\wwwroot).

I will appreciate it if anyone helps me with this issue.

**Comment by opensource008** [comment]
If you want to check remotely running on local I think the right port is 5000
localhost:5000

**Comment by Peace569** [comment]
OK, thanks
