### ISSUE TITLE
Windows instant support client links are dead on website

### ISSUE THREAD

**Issue by frogcrush** [lucent-sea/Remotely#305]
**Describe the bug**
Windows "Instant Support Client" links on the websites are dead links. Linux quick support link works.

**To Reproduce**
1. Go to https://remotely.one/#portableClients
2. Click on "Windows (x64) or Windows (x32)
3. You are redirected to a dead link

**Expected Behavior**
You should be able to successfully download the quick support clients from the website.

**Screenshots**
![image](https://user-images.githubusercontent.com/6116333/115771590-252e5e00-a37c-11eb-9b19-19913da1bb3b.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Edge
 - Version 90

**Comment by frogcrush** [comment]
Update: Changing "Downloads" to "Content" in the URL allows you to download the installer. Appears to be related to the latest release then?

**Comment by lucent-sea** [comment]
Thanks for letting me know!  :)  Yes, this was due to the URL change, and I forgot to update the links.  I've pushed an update.

Cheers!
