### ISSUE TITLE
Is there any way that can increase the streaming speed ?

### ISSUE THREAD

**Issue by Peace569** [lucent-sea/Remotely#309]
This project speed is slower than TeamViewer or Anydesk.
Sorry, but could you increase the streaming speed?

**Comment by lucent-sea** [comment]
I've been looking for a cross-platform video encoding solution for .NET that would be relatively easy to implement and fits the licensing model.  I've yet to find one, though.

This is a hobby project that I develop in between working full-time (my real job) and raising a family.  So I have very limited time I can spend on the project.  If the project generated enough money to where I could work on it full-time, then I'd definitely learn how to write my own native, hardware-accelerated video encoding libraries for each OS.  

But for now, I only have time for low-effort solutions.
