### ISSUE TITLE
Remotely on Raspberry Pi

### ISSUE THREAD

**Issue by jannis3005** [lucent-sea/Remotely#318]
**Is your feature request related to a problem? Please describe.**
I'm looking into at least trying to setup Remotely on a Raspberry Pi 4 (64bit arm). Since the provided installer is only x86, i'm not really sure if this is even possible.

**Describe the solution you'd like**
I guess the optimal solution would be a working installer for Arm. But a hint on how to manage to compile this (if even possible) would also be enough.

**Describe alternatives you've considered**
I've looked into trying to build one myself eventhough im not really sure on how to maybe achieve this, since i've never done anything with .net before, so i have not managed to to do this yet.

**Comment by lucent-sea** [comment]
This will give you a Linux ARM build of the agent:

```
git clone https://github.com/lucent-sea/remotely
cd ./remotely

$VersionString = git show -s --format=%ci
$VersionDate = [DateTimeOffset]::Parse($VersionString)

$Year = $VersionDate.Year.ToString()
$Month = $VersionDate.Month.ToString().PadLeft(2, "0")
$Day = $VersionDate.Day.ToString().PadLeft(2, "0")
$Hour = $VersionDate.Hour.ToString().PadLeft(2, "0")
$Minute = $VersionDate.Minute.ToString().PadLeft(2, "0")
$CurrentVersion = "$Year.$Month.$Day.$Hour$Minute"

cd ./Agent

dotnet publish /p:Version=$CurrentVersion /p:FileVersion=$CurrentVersion --runtime linux-arm --configuration Release --output ".\publish"
```

However, it will still be missing dependencies that can't be bundled with Remotely and need to be installed via package manager.  Trying to support various Linux distros is extremely time-consuming and benefits a much smaller group than Windows or Mac.  As such, only Ubuntu (with X11 for remote control) will be supported.  I don't have the time to support distros.

**Comment by EliteEng** [comment]
@lucent-sea thanks for all the great work you are doing.
I have created a build for the Rpi4 running Ubuntu Arm 64, and all seems to be working correctly.
The computer shows up on the dashboard with details, etc.

But when I click Actions / Remote Control from the dashboard, I get a red error box saying "Executable not found on device"
Would you be able to point me in the right direction to finding a fix.
