### ISSUE TITLE
Remotely Server behind NAT & reverse proxy

### ISSUE THREAD

**Issue by assassin78** [lucent-sea/Remotely#320]
hello, is there any config should i do to get remotley server to work properly its keep disconnecteing every 3 seconds, see picture below

thank you in advance

![image](https://user-images.githubusercontent.com/32180179/116228090-6049dc00-a744-11eb-937f-d4f7cbaf63c4.png)

**Comment by jmilette** [comment]
Not nearly enough details on this.  NAT/reverse proxy setups work fine, something is most likely misconfigured with your setup.  What reverse proxy are you using, what config are using for it, how is your domain managed?  My best guess is the websocket connections aren't being proxied correctly, which would be a config issue.  Might be worth trying out the new installer - it bundles everything including configs for the reverse proxies.

**Comment by stevesobol** [comment]
@assassin78 I know Jared supports using Remotely with nginx. haproxy is not "officially" supported, but I use haproxy and have gotten it to work with Remotely, and it's actually pretty simple. So, if you're using haproxy, I can help.

**Comment by aznkvaj** [comment]
I was having the same issue. I can't be behind a NAT and forward the service through a reverse proxy to the dedicated server.
I just gave up and pointing to the Nginx server on the same system with remotely installed.

**Comment by lucent-sea** [comment]
Thanks, @stevesobol.

I'm on mobile and have been ill, so please excuse the short reply.

I've only tested with having the reverse proxy on the same box. But there are 4 SignalR endpoints that need special handling to get upgraded to websocket connections. My guess is it's not getting upgraded somewhere. 

Another possible issue is if the proxy server's IP address isn't in the KnownProxies list. In that case, it won't accept forwarded headers, and things won't work right.

Perhaps additional configuration is needed. I thought I had the minimum required for the setup, though. 

Additional info: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0

**Comment by assassin78** [comment]
@jmilette  @stevesobol @aznkvaj @lucent-sea 
thanks everyone for the response and support this is my setup :

- container with Ngnix Reverse Proxy Manager
- container with Remotely
- container with Ticket System

the reverse proxy is behind nat with port 443 and 80 being opened to the public internet

that's everything i have so far, thanks again for the help

**Comment by assassin78** [comment]
hello everyone i found the issue in my configuration off nginx reverse proxy manager i forgot to enable Websockets Support once activated everything is working perfectly

![image](https://user-images.githubusercontent.com/32180179/116558006-857a4e00-a8ee-11eb-864f-648e7fde1c72.png)

thank you all

**Comment by lucent-sea** [comment]
Thanks for reporting back!  :)

**Comment by Jenni32222** [comment]
hey @assassin78, how did you get remotely to work with nginx proxy manager? I'm having issues, could you please share your config?
