### ISSUE TITLE
How can I use Video Streaming.

### ISSUE THREAD

**Issue by Peace569** [lucent-sea/Remotely#328]
Hello, @lucent-sea 
Now there is a WebRTC Video Streaming Code in this project.
But it is not used in peer connection now.
If we use it, I think we can increase the video quality and streaming speed.
How can I implement all webRTC streaming via Video Streaming?
Regards.

**Comment by lucent-sea** [comment]
There is a Stream Mode button on the sidebar that will switch to WebRTC video streaming.  It's only available if you were able to get a WebRTC connection, though.  However, if you add a TURN server to the ICE servers list, you will almost always get a WebRTC connection.  Even if it's relayed through TURN, the streaming will still work.

![image](https://user-images.githubusercontent.com/20995508/117300708-abdc4400-ae2e-11eb-9b66-0b4c19a29b4a.png)
