### ISSUE TITLE
.NET Deployment Question

### ISSUE THREAD

**Issue by opensource008** [lucent-sea/Remotely#330]
Good Day,

To All,

Looking for your kind assistance,
Want to clarify my understanding to the .net deployment.  if there is an option to the (portable) quick support and to the agent installer that no need to install .net framework to the computer?, 

if yes how can I build the installer ? 
![IMG_20210501_073926](https://user-images.githubusercontent.com/78790472/116763757-3993ea00-aa51-11eb-904c-91cbc76d0e4d.jpg)

thank you

**Comment by lucent-sea** [comment]
The quick support client is already completely self-contained.  It doesn't require any version of .NET to be installed.

The agent installer is the only remaining part of Remotely that is .NET Framework.  It requires version 4.8 to be installed.  I'll be replacing this eventually with a cross-platform, self-contained installer.
