### ISSUE TITLE
Suggestion only for new GUI

### ISSUE THREAD

**Issue by opensource008** [lucent-sea/Remotely#331]
Good Day,

First the new update and gui is sweet another great work sir jared,

1. only want to suggest if possible , when you opening or maximize the device to open or to see the actions button is you need to click computer name. if also ok to add that if you click again the computer name it will close the device.
![IMG_20210501_075947](https://user-images.githubusercontent.com/78790472/116764512-e8d1c080-aa53-11eb-957c-172638ffe101.jpg)

2. if its ok to back the remote control request button beside search box, before there is button only need is to check the device and click the remote control to request the access no need to open the actions button.

thank you and more power

**Comment by lucent-sea** [comment]
Thanks for the suggestion.  I added this.
