### ISSUE TITLE
For Docker version, auto-configure client binary with server URL

### ISSUE THREAD

**Issue by heurekus** [lucent-sea/Remotely#332]
I have deployed a Docker instance of the Remotely server. When a client downloads the client binary, it's necessary to manually change the server URL before connecting. Not a big deal but a challenge for some people that need PC support.

Suggestion: For the docker version of the server, it would be nice if the client was auto-configured wiht the server URL. The URL for the server could be given in an environment variable as part of the docker command.

**Comment by lucent-sea** [comment]
I've talked about this briefly here:  https://github.com/lucent-sea/Remotely/discussions/197

The only way to "embed extra data" into an EXE is to append the bytes to the end of it, but it breaks the digital signature.  That would be bad for people who are signing their binaries.

The only other way to achieve this is if I hosted a service for everyone that recompiled the EXE on demand, after modifying the source code to embed your server URL.  This wouldn't be feasible or scalable.  Plus it would defeat the purpose of being self-hosted if it relied on an external service.

For now, the only way to avoid having to enter the server URL is to use the server installer tool, which will call into GitHub Actions to build a customized server package.  The clients within it will have the server URL embedded in them.
