### ISSUE TITLE
Server Log

### ISSUE THREAD

**Issue by opensource008** [lucent-sea/Remotely#335]
Good Day,

Noticed this on server log.
1.  
![image](https://user-images.githubusercontent.com/78790472/116840733-976b3200-ac09-11eb-8162-f9ca5ffc04eb.png)

2.
![image](https://user-images.githubusercontent.com/78790472/116840793-c97c9400-ac09-11eb-80b5-8961ad7e6395.png)

**Comment by lucent-sea** [comment]
The first one is normal.

I could replicate 2, and I'm not seeing it on any other servers.  It's possible that another process had locked the file, especially if you're using command line tools or GUIs like DB Browser for SQL Lite to view/edit the database.

**Comment by opensource008** [comment]
> The first one is normal.
> 
> I could replicate 2, and I'm not seeing it on any other servers. It's possible that another process had locked the file, especially if you're using command line tools or GUIs like DB Browser for SQL Lite to view/edit the database.

thank you @lucent-sea  sir, but im not using any editing tools for sqllite,
