### ISSUE TITLE
Resolution / Color Depth

### ISSUE THREAD

**Issue by kingfenix** [lucent-sea/Remotely#338]
**Is your feature request related to a problem? Please describe.**
I am seeing pixelization and color distortion and resolution issues, are there or can there be settings to enhance/control this?

**Describe the solution you'd like**
Most remote control apps have somewhere you can set preferred settings for color depth, quality and resolution to scale or be a certain size, could this happen here?

**Describe alternatives you've considered**
I have explored the interface and cannot find anything currently implemented to help with this. Am I blind?

**Additional context**

**Comment by lucent-sea** [comment]
I added a toggle for Auto Quality in the sidebar.  With it turned off, it will not automatically reduce quality based on latency and connection speed.

For the best quality and bandwidth utilization, I recommend using Stream Mode when available (which uses WebRTC video).  You can replace the STUN servers with a TURN server in the ICE servers list to ensure WebRTC is almost always available.

However, I'm not going to invest time into additional quality options until I'm sure of what will be used for video/image encoding in the future.

**Comment by kingfenix** [comment]
I have tried both latest and preview, and do not see this new auto quality feature. Also the about still says 4/29, so the docker isnt getting the new version anywhere?
