### ISSUE TITLE
Update Docker Container

### ISSUE THREAD

**Issue by kingfenix** [lucent-sea/Remotely#339]
**Is your feature request related to a problem? Please describe.**
Docker container is not on current release of 4/29

**Describe the solution you'd like**
Please update the docker container release (UNRAID)

**Describe alternatives you've considered**

**Additional context**

**Comment by kingfenix** [comment]
ok, the container is now updated...but this made me discover a bug in that process. I was on the 3/29 container, and now post update I am on the 4/29 version. The problem is that I had to reinstall my unattended clients to join a new organization ID, and reconfigure everything again on the new container. Is there no way to persist these settings between upgrades of the container?

**Comment by lucent-sea** [comment]
It's not currently using the volume to persist data. I need to add it later.  The readme Docker Hub shows how to backup and restore data between upgrades.

![image](https://user-images.githubusercontent.com/20995508/116926177-eff0fe00-ac0e-11eb-929e-aa0e3faebfed.png)
