### ISSUE TITLE
manage organizations and devices

### ISSUE THREAD

**Issue by skadefro** [lucent-sea/Remotely#344]
**Is your feature request related to a problem? Please describe.**
I've shared my install of remotely with a few customers, and I now they shared it with a few friends and companies as well. But there is no interface for me to see what Organizations have been created, nor a way to manage and/or delete unwanted Organizations.
When I need to support a customer, I first need to tell them how to create an account, that will create an Organizations, then I need to guide them on how to add a user for me, and then I need to maintain a list of separate users and passwords per org, that is bad for a lot of reasons.

**Describe the solution you'd like**
Please add a "swap to Organization" drop down list, somewhere in the UI, so when we are signed in as ServerAdmin, we can easily swap to any organization and manage it. (users, devices etc)

**Comment by lucent-sea** [comment]
There might be a misunderstanding here of the intent of Organizations.

The primary reason for Organizations is for offering the server as a SaaS product, like how https://app.remotely.one is set up.  People can register on their own and start adding devices.  Their organization is completely separated from others, and even the server administrator (me) doesn't have access to it.

The people creating Organizations are presumed to be MSPs or other IT shops.  The devices they add are their customers' devices, which they manage on their behalf.

If I, as the server administrator, could switch over to their organization and start remoting into their customers' machines, then that would be bad.  And I assume nobody would want me to have the ability to do that.

If you need permanent, unattended access to your customer's device, you should install the service and have it connect to your organization.  Then you're an IT administrator of that device.  Then you can create Device Groups if you want to group devices by customer's company.

If you need ad-hoc, attended access, they should download one of the quick support clients.

Hope that helps!

**Comment by skadefro** [comment]
That does not help no.
I use remotely so customers can manage unattended robots on remote desktop servers.( so claiming downloading the adhoc client solve this makes no sense )  I dont want different customers can access each others servers ( so using one big org does not make sense either), but they should still be able to manage their own while i should  be able to also manage them.
Seems weird to just close with even asking for the use case.
I get how YOU are using it, but nothing stops you from making it a boolean value in the config file to sllow for different use cases.

**Comment by lucent-sea** [comment]
I closed it because it's not something I wish to be added to the codebase.

**Comment by lucent-sea** [comment]
> I dont want different customers can access each others servers ( so using one big org does not make sense either),

You can restrict users to specific device groups, so they can only see/manage  the ones in those groups.

**Comment by skadefro** [comment]
Hey.
Just testet it. That will fix my request, thank you.
