### ISSUE TITLE
New version Docker container broken

### ISSUE THREAD

**Issue by kingfenix** [lucent-sea/Remotely#346]
Just upgraded to new container this morning, and now the container will not start in UNRAID, following message is seen when starting/installing

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='remotely' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -p '9280:5000/tcp' -v '/mnt/cache/appdata/remotely':'/remotely-data':'rw' 'translucency/remotely'

a360922703162220b64a7e53dccdc1b5f6f77f1b8822d8d3f6c5da5b1e1963c2
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/DockerMain.sh": permission denied: unknown.

The command failed.

**Comment by kingfenix** [comment]
maybe the command just needs to be docker run instead of docker create?

**Comment by kingfenix** [comment]
maybe the command just needs to be docker run instead of docker create?

**Comment by lucent-sea** [comment]
Looks like permissions just needed to be set on the file.

I created a `preview` tag, which I'll use from now on before publishing latest.  The preview one seems to be working now.  I'll publish `latest` now too.

Also, I got the volume working.  Both the `appsettings.json` and `Remotely.db` files will use it now.

**Comment by kingfenix** [comment]
thats awesome, THANK YOU!

**Comment by lucent-sea** [comment]
For sure.  :)  Let me know if there are still issues.

**Comment by lucent-sea** [comment]
Oh, and you'll probably need to manually copy your database to the volume the first time.
