### ISSUE TITLE
Memory leak under IIS

### ISSUE THREAD

**Issue by dsinfinite** [lucent-sea/Remotely#347]
**Describe the bug**
Remotely iis site leaking memory

**To Reproduce**
1. Use remotely
2. 
**Remotely Version**
Server: 2021.04.29.0747
Agent: Various

**Expected Behavior**
No memory leak

**Screenshots**

![image](https://user-images.githubusercontent.com/59153350/117334054-8d466f00-ae67-11eb-9a64-926a55ae7118.png)

Please let me know what other information I can provide - Had to kill w3wp.exe to get server back alive.

**Comment by lucent-sea** [comment]
Could you please provide the following info to help in reproducing?

- Windows Version
- Agent Count
- Length of time passed to produce above memory usage
- Any significant errors in the server log?
- Windows Event Log enabled in appsettings?
- DB Provider
- Any additional infrastructure between server and internet?

Thanks!

**Comment by lucent-sea** [comment]
Oh, and web config please.  :)

**Comment by dsinfinite** [comment]
*   Windows Version - Microsoft Windows Server 2019 Standard 10.0.17763
  *   Agent Count: 507
  *   Length of time passed to produce above memory usage – 4 days
  *   Any significant errors in the server log? – Nope
  *   Windows Event Log enabled in appsettings? - Nope
  *   DB Provider - sqlite
  *   Any additional infrastructure between server and internet? – Nope. Running on IIS server – the server is also used for ARR though.


Web.config:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath=".\Remotely_Server.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>


Since restarting memory usage jumped from 90MB to 180MB. Will see if I starting a remote session causes it to increase.

Thanks!

**Comment by dsinfinite** [comment]
Errors in server logs would help though!

This is where the errors started:

<html>
<body>


Error | 5/4/2021 9:42:16 AM -04:00 | [Error] [TransportConnectionId:zZpKVpXoWGBWB1CkvJ52sw - RequestPath:/AgentHub/negotiate RequestId:80000024-0002-6e00-b63f-84710c7967bb - Remotely.Server.Hubs.CircuitConnection] \| Message: Error while invoking circuit event. \| Exception: Object reference not set to an instance of an object. |   | at Remotely.Server.Components.Devices.DevicesFrame.<>c.<FilterDevices>b__57_0(Device x) in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor.cs:line 259 at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match) at Remotely.Server.Components.Devices.DevicesFrame.FilterDevices() in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor.cs:line 234 at Remotely.Server.Components.Devices.DevicesFrame.Refresh() in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor.cs:line 93 at Remotely.Server.Components.Devices.DevicesFrame.CircuitConnection_MessageReceived(Object sender, CircuitEvent args) in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor.cs:line 156 at Remotely.Server.Hubs.CircuitConnection.ProcessMessages() in D:\a\Remotely\Remotely\Server\Hubs\CircuitConnection.cs:line 415
-- | -- | -- | -- | --



</body>
</html>



<html>
<body>


Error | 5/4/2021 10:17:18 AM -04:00 | [Error] [TransportConnectionId:zUcWSTIuDV0s-pGPuogZOQ - RequestPath:/AgentHub/negotiate RequestId:80000024-0002-6e00-b63f-84710c7967bb - Remotely.Server.Hubs.CircuitConnection] \| Message: Error while invoking circuit event. \| Exception: Failed to compare two elements in the array. |   | at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer) at System.Collections.Generic.List`1.Sort(Comparison`1 comparison) at Remotely.Server.Components.Devices.DevicesFrame.FilterDevices() in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor.cs:line 234 at Remotely.Server.Components.Devices.DevicesFrame.Refresh() in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor.cs:line 93 at Remotely.Server.Components.Devices.DevicesFrame.CircuitConnection_MessageReceived(Object sender, CircuitEvent args) in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor.cs:line 156 at Remotely.Server.Hubs.CircuitConnection.ProcessMessages() in D:\a\Remotely\Remotely\Server\Hubs\CircuitConnection.cs:line 415
-- | -- | -- | -- | --



</body>
</html>

<html>
<body>


Error | 5/4/2021 11:27:38 AM -04:00 | [Error] [TransportConnectionId:9Nko41e49fEXXL3KqoTVqg - RequestPath:/AgentHub/negotiate RequestId:80000024-0002-6e00-b63f-84710c7967bb - Remotely.Server.Hubs.CircuitConnection] \| Message: Error while invoking circuit event. \| Exception: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Comparison`1[Remotely.Shared.Models.Device]'. |   | at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer) at System.Collections.Generic.List`1.Sort(Comparison`1 comparison) at Remotely.Server.Components.Devices.DevicesFrame.FilterDevices() in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor.cs:line 234 at Remotely.Server.Components.Devices.DevicesFrame.Refresh() in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor.cs:line 93 at Remotely.Server.Components.Devices.DevicesFrame.CircuitConnection_MessageReceived(Object sender, CircuitEvent args) in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor.cs:line 156 at Remotely.Server.Hubs.CircuitConnection.ProcessMessages() in D:\a\Remotely\Remotely\Server\Hubs\CircuitConnection.cs:line 415
-- | -- | -- | -- | --



</body>
</html>

<html>
<body>


Warning | 5/4/2021 1:47:28 PM -04:00 | [Warning] [TransportConnectionId:3XtLkzyF85Zn-RUE1hBneQ - RequestPath:/AgentHub/negotiate RequestId:80000024-0002-6e00-b63f-84710c7967bb - Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer] \| Message: Unhandled exception rendering component: Collection was modified; enumeration operation may not execute. \| Exception: Collection was modified; enumeration operation may not execute. |   | at System.Collections.Generic.List`1.Enumerator.MoveNextRare() at System.Linq.Enumerable.WhereListIterator`1.MoveNext() at System.Linq.Set`1.UnionWith(IEnumerable`1 other) at System.Linq.Enumerable.ExceptIterator[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)+MoveNext() at System.Linq.Enumerable.EnumerablePartition`1.MoveNext() at System.Linq.Enumerable.ConcatIterator`1.MoveNext() at Remotely.Server.Components.Devices.DevicesFrame.BuildRenderTree(RenderTreeBuilder __builder) in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor:line 83 at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment) at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry) at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
-- | -- | -- | -- | --



</body>
</html>

<html>
<body>


Warning | 5/4/2021 4:13:14 PM -04:00 | [Warning] [RequestPath:/_blazor/negotiate RequestId:80000066-0004-b200-b63f-84710c7967bb - RequestPath:/AgentHub/negotiate RequestId:80000024-0002-6e00-b63f-84710c7967bb - Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer] \| Message: Unhandled exception rendering component: Exception of type 'System.OutOfMemoryException' was thrown. \| Exception: Exception of type 'System.OutOfMemoryException' was thrown. |   | at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength) at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity) at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.RemoveOldFrame(DiffContext& diffContext, Int32 oldFrameIndex) at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl) at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree) at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment) at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry) at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
-- | -- | -- | -- | --



</body>
</html>



This is the final set that caused everything to crap out:

<html>
<body>


Error | 5/6/2021 12:33:01 PM -04:00 | [Error] [RequestPath:/AgentHub/negotiate RequestId:800003cc-0000-9600-b63f-84710c7967bb - RequestPath:/AgentHub RequestId:8000001c-0006-f400-b63f-84710c7967bb - Microsoft.AspNetCore.SignalR.HubConnectionHandler] \| Message: Error when dispatching 'OnDisconnectedAsync' on hub. \| Exception: SQLite Error 5: 'database is locked'. |   | at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db) at Microsoft.Data.Sqlite.SqliteDataReader.NextResult() at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior) at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery() at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters) at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred) at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel, Boolean deferred) at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel) at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection) at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave) at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess) at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) at Remotely.Server.Services.DataService.DeviceDisconnected(String deviceID) in D:\a\Remotely\Remotely\Server\Services\DataService.cs:line 934 at Remotely.Server.Hubs.AgentHub.OnDisconnectedAsync(Exception exception) in D:\a\Remotely\Remotely\Server\Hubs\AgentHub.cs:line 215 at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception) at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception) at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.HubOnDisconnectedAsync(HubConnectionContext connection, Exception exception)
-- | -- | -- | -- | --
Warning | 5/6/2021 12:33:01 PM -04:00 | [Warning] [RequestPath:/AgentHub RequestId:8000000c-0007-ec00-b63f-84710c7967bb - RequestPath:/AgentHub RequestId:8000001c-0006-f400-b63f-84710c7967bb - Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer] \| Message: Unhandled exception rendering component: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray') \| Exception: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray') |   | at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable) at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length) at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity) at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.RemoveOldFrame(DiffContext& diffContext, Int32 oldFrameIndex) at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl) at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree) at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment) at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry) at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
Error | 5/6/2021 12:22:44 PM -04:00 | [Error] [TransportConnectionId:f_HzOBrLDaACJu7fk5nHmg - RequestPath:/AgentHub RequestId:8000001c-0006-f400-b63f-84710c7967bb - Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost] \| Message: Unhandled exception in circuit 'WjjaudgI9YG3oSVGChsWBcaOn0JgxeACIfhPzLilB2s'. \| Exception: Collection was modified; enumeration operation may not execute. |   | at System.Collections.Generic.List`1.Enumerator.MoveNextRare() at System.Linq.Enumerable.WhereListIterator`1.MoveNext() at System.Linq.Set`1.UnionWith(IEnumerable`1 other) at System.Linq.Enumerable.ExceptIterator[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)+MoveNext() at System.Linq.Enumerable.EnumerablePartition`1.MoveNext() at System.Linq.Enumerable.ConcatIterator`1.MoveNext() at Remotely.Server.Components.Devices.DevicesFrame.BuildRenderTree(RenderTreeBuilder __builder) in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor:line 83 at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment) at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry) at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
Warning | 5/6/2021 12:22:44 PM -04:00 | [Warning] [TransportConnectionId:f_HzOBrLDaACJu7fk5nHmg - RequestPath:/AgentHub RequestId:8000001c-0006-f400-b63f-84710c7967bb - Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer] \| Message: Unhandled exception rendering component: Collection was modified; enumeration operation may not execute. \| Exception: Collection was modified; enumeration operation may not execute. |   | at System.Collections.Generic.List`1.Enumerator.MoveNextRare() at System.Linq.Enumerable.WhereListIterator`1.MoveNext() at System.Linq.Set`1.UnionWith(IEnumerable`1 other) at System.Linq.Enumerable.ExceptIterator[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)+MoveNext() at System.Linq.Enumerable.EnumerablePartition`1.MoveNext() at System.Linq.Enumerable.ConcatIterator`1.MoveNext() at Remotely.Server.Components.Devices.DevicesFrame.BuildRenderTree(RenderTreeBuilder __builder) in D:\a\Remotely\Remotely\Server\Components\Devices\DevicesFrame.razor:line 83 at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment) at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry) at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()


</body>
</html>

**Comment by dsinfinite** [comment]
***@***.***D74322.6E984160]

Since restarting the service memory is steady again at 180MB. If it happens again what can I do to help trace the cause?

**Comment by opensource008** [comment]
https://github.com/lucent-sea/Remotely/issues/256

think this also related to my previous post, I encounter when I restart my server and there is 200+ agent online (physical computer)  100% memory usage on server

To check if i have low memory i added memory from 6 to 15gb but when server boot up still encounter 99% memory usage.

my workaround is to replace again all installation files like if you did upgrade only files ratain is the database sqllte and appsettngs.

Linux 20.04
4core cpu
6gb memory

**Comment by lucent-sea** [comment]
I set up a Windows Server 2016 server and have had it running for a few days.  I haven't noticed any memory issues yet.

I'm not sure how to effectively debug if it happens again.  You could try creating a dump of the w3wp, but it probably wouldn't be successful if the memory has grown to that size.  And transferring it would be difficult.  But if you manage to catch it at a smaller memory footprint, there might be something telling in it.  Not sure, though.

I could add instrumentation to Remotely, but I don't think that would reveal anything.  If it were the Remotely assembly itself with the memory leak, I think I would have seen it on my public server by now.

**Comment by dsinfinite** [comment]
Thanks. Memory still seems stable. If it happens again I will attempt to get a dump.
