### ISSUE TITLE
Remotely sends AUTH to SMTP server when it's not needed.

### ISSUE THREAD

**Issue by Drehmini** [lucent-sea/Remotely#354]
__Describe the bug__
Remotely assumes that  the SMTP server that is configured requires a username/password.
This prevents an administrator from configuring a SMTP server that has the remotely server set up as a "Forwarding Host" or relay.

__To Reproduce__
1. Configure remotely to use an SMTP that does not require authentication
2. Run the SMTP server test

__Remotely Version__
2021.04.29.0623

__Expected Behavior__
Ideally, if no values are put in the config, Remotely should not try to send an AUTH command to the SMTP server.
Huginn deals with this by requiring that you use "none" for the username to ensure that AUTH is not sent.

__Additional Context__
Here's the error that is generated in the LOG.

Error | 05/11/2021 21:57:12 +00:00 | The SMTP server does not support authentication. | MailKit | at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken) at Remotely.Server.Services.EmailSenderEx.SendEmailAsync(String toEmail, String replyTo, String subject, String htmlMessage, String organizationID) in D:\a\1\s\Server\Services\EmailSender.cs:line 54
-- | -- | -- | -- | --

The reference for line 54 in EmailSender.cs is here:
https://github.com/lucent-sea/Remotely/blob/38bd21b77b861c64e8621056fefb644dd5d4aebc/Server/Services/EmailSender.cs#L54

You can reference the Mailkit devs talking about this exact issue here: https://github.com/jstedfast/MailKit/issues/1049#issuecomment-662474185

**Comment by lucent-sea** [comment]
The latest release include this, but I'm not able to test it.  Please let me know if it works out for you.  :)

**Comment by lucent-sea** [comment]
Author reported this as closed in Reddit.
