### ISSUE TITLE
Hi CPU usage whe more of four users are using the interface

### ISSUE THREAD

**Issue by telluria-raphael-advincula** [lucent-sea/Remotely#356]
After migrating to Blazor, CPU utilization remains high when more than 3 users use the tool at the same time.
The increase in CPU usage now occurs when users manipulate server boxes.
We migrated remotely to a cloud server with four vCPUS and 8GB of ram, and yet the .net process uses 100% CPU a few times and this locks the interface for all users

**To Reproduce**
1. Install remotely
2. Ask more than 4 users to use the interface at the same time.
3. Run the top command on the Linux terminal
4. See the CPU usage increase up to 100% and the remotely web interface freeze

**Remotely Version**
Server : I'm using the master branch version whith the "Bind device search filter on change instead of on input." bugfix

**Expected Behavior**
A CPU usage that doesn't sacrifice the performance of the web interface

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser chrome
 - Version  90.0.4430.212 
 - We are using a server with 4vCpus and 8gb of Ram (Remembering that with the previous version a server with 2vCPUS worked like a charm.)

**Additional Context**
  - In my tests this bugfix solved the searchbox problem (https://github.com/lucent-sea/Remotely/issues/355) 
  - However, using the interface with more than 4 people is practically impossible due to spikes in CPU consumption.

**Comment by opensource008** [comment]
before i encountered the problem but after migrate remotely server to ubuntu 20.04 no problem with 10 users concurrent users (interface)

**Comment by lucent-sea** [comment]
I understand that there's more CPU usage now that things are being rendered server-side, and I'm sorry that it's affected your experience so much.  I haven't been able to replicate the level that you're talking about, but I think I see how it could be happening.

I've made some adjustments that will hopefully help in your situation.

- Device heartbeats (every 5 minutes), devices going offline, and devices coming online no longer trigger a full refresh and re-sort of the devices list.
  - If you have a lot of devices, or any devices that are going online/offline frequently, this could have been using a lot of the CPU for re-rendering the device cards.
- Device cards that are currently visible will still be updated.
- A `Refresh` button was added to manually do a full reload and re-sort of the devices, using the currently-selected options (i.e. doesn't reset any sort/filter/search/etc. controls).
- Default devices per page was reduced to 25.
- Using any of the sort, filter, page, or search controls will still do a full refresh, so you don't have to do both.

**Comment by telluria-raphael-advincula** [comment]
Hello, these modifications allowed us to successfully update remotely's version.

**Comment by telluria-raphael-advincula** [comment]
Thank you very much!

**Comment by lucent-sea** [comment]
Thanks for following up and letting me know!  :)
