### ISSUE TITLE
Shift and Strg Key dosn't work

### ISSUE THREAD

**Issue by Tommy-01** [lucent-sea/Remotely#358]
Using:
Client
Instant Support Client - Linux 64bit
Version "Up-to-date" 25.07.2021

Server
Public Server
https://app.remotely.one/RemoteControl

German Keyboard Layout on both machines.

Steps to reproduce:
1. Connect to Client
2. Open a Software on the Client to type some Text
3. Hold Shift an type a letter
The letter will be lowercase.

Expected behavior:
The letter will be uppercase.

Same behavior with the Strg Key. For example using the STRG+C and V Command to Copy and Paste something.
The Strg Key will also not be noticed by the Client.

**Comment by lucent-sea** [comment]
Remotely currently only works with en-US keyboard and regional settings.
