### ISSUE TITLE
When unattended access fails - enhancement request

### ISSUE THREAD

**Issue by swilkey** [lucent-sea/Remotely#81]
Hi Jared,

I have a suggestion to protect security of devices being remote controlled.  I've seen other similar solutions do this in the past.  If a person is remote controlling a machine using unattended access and they end their connection or their connection is ended prematurely, the machine could be left in an insecure state because it will remain unlocked, the way the person was using it.  It would be great if when the connection terminates, the agent could automatically issue a WINDOWS-L on the controlled device to lock it so that it doesn't leave it insecure.

Thanks,
Stephen

**Comment by Jay-Rad** [comment]
I'll look into adding this.

**Comment by swilkey** [comment]
Thanks Jared

**Comment by Nonobis** [comment]
Hello jared,

I like the idea of swilkey, it's more secure but could it be optional ?
Thanks

**Comment by lucent-sea** [comment]
Please request at https://remotely.featureupvote.com/.  I can only work on one bug or feature at a time.   A voting system helps determine which features gets attention first.
