### ISSUE TITLE
Requested documentation change (with suggested changes)

### ISSUE THREAD

**Issue by swilkey** [lucent-sea/Remotely#84]
Hi Jared,

I am writing to suggest a few changes to the documentation in README.md so that people don't have to do as much research and testing as I did when I first set this up.  Each of the suggested changes is because they are things that I needed to research before I could implement the solution, so providing the information may save future people that time and make the threshold for adoption easier for people.

I hope this helps.
Stephen

---
IN THE EXISTING DOCUMENTATION:
Client Prerequisites:
Endpoint devices require the .NET Core runtime to be installed.
For Windows, the Desktop Runtime is required.
Download Link: https://dotnet.microsoft.com/download/dotnet-core/current/runtime

SUGGESTED ADDITION:
Note that if the dotnet runtime is not already installed on the computer at the time of installing the either the instant client software or the unattended agent service, the installation will download it (in the case of the instant client it will offer to download it, in the case of the unattended client it will download it automatically).  If you want to install it locally so that users don't cause unnecessary downloads from the internet, just create a batchfile that runs the installation of remotely and before installing remotely, install the dotnet runtime - if it is already installed it will recognise that and skip reinstallation. eg.
@echo off
echo Checking for the latest .NET runtime and installing it if required...
windowsdesktop-runtime-3.1.2-win-x64.exe /quiet
echo Installing remotely remote control tool...
Remotely_Installer-YOUR_ORGANISATION_GUID_HERE.exe -install -path Remotely-Win10-x64.zip
echo Installation is finished.
Note that the URL of the server is set in the Remotely agent installer when you use publish.ps1 to build it, but the Organisation GUID is obtained by the agent from the name of the executable for the installer, so if you rename the executable to make it prettier by removing the guid, the installer will no longer know the guid for your organisation.  (note that the instant client only needs your server URL and it gets this at build time, so if you do not build your own server files with publish.ps1, the default files you install using the server installation script will have this undefined and the user will be prompted to enter the server URL the first time they run it)

IN THE EXISTING DOCUMENTATION:
Session Recording
You can turn on session recording in appsettings.json.
The following requirements must be met for it to work:
On Linux, libgdiplus and libc6-dev must be installed (sudo apt-get install libgdiplus libc6-dev).
The process running the app must have access to create and modify a folder name "Recordings" in the site's root content folder.
FFmpeg must be executable from the process running the Remotely server.
Link: https://www.ffmpeg.org/download.html

SUGGESTED ADDITION:
Note that session recording is not possible for individual sessions.  It is designed to be done for all sessions as a quality control/security measure, or no sessions.

IN THE EXISTING DOCUMENTATION:
.NET Core Deployments
.NET Core has two methods of deployment: framework-dependent and self-contained.
Framework-dependent deployments require the .NET Core runtime to be installed on the target computers. It must be the same version or higher that was used to build the app.
Self-contained deployments include a copy of the runtime, so you don't need to install it on the target computers. As a result, the total file size is much larger.
.NET Core uses runtime identifiers that are targeted when building.
Link: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

SUGGESTED ADDITION:
You can refer to https://docs.microsoft.com/en-us/dotnet/core/deploying/ to understand the differences between the framework-dependent and self-contained methods.  Note that the files that are built using publish.ps1 are framework-dependent deployments.  This has the advantage of being a smaller file to distribute, and also means that we rely on Windows to ensure that the framework is kept up-to-date rather than needing to update the self-contained version ourselves when new versions are released.

**Comment by swilkey** [comment]
Additional suggested documentation ADDITION:

The Grid and the Console
The Grid the the Console both provide a way of selecting clients and taking actions with those selections.  What you select in one remains valid when you switch to the other.

The Grid allows you to chat, remote control or to update information about a client.  The console has 5 modes.  In each mode the command "help" will give you information about the commands available to you.  These modes are selectable from a dropdown menu at the bottom left of the console window.

Console-Web
The web console allows you to do everything you can do from the grid, plus more, including scripted selection of clients, removal of clients, uninstallation of clients, transferring files between you and the clients and running scripts on the clients.

Console-PSCore
Sorry, I don't know what this is useful for.

Console-WinPS
This is direct access to the powershell on a single selected Windows computer.

Console-CMD
This is direct access to the CMD prompt on a single selected Windows computer.

Console-Bash
This is direct access to the bash prompt on a single selected Linux computer.  Note that if you have Windows Subsystem for Linux installed on your Windows computer and therefore have a bash prompt, this will not allow you to interact with it.  If you need to run a bash command on it, use the methods documented in the Microsoft WSL documentation to run that bash command from the CMD or Powershell prompt.

**Comment by swilkey** [comment]
I also made some further updates to my first post above.

**Comment by Jay-Rad** [comment]
Thanks for all this feedback!  I'll work on updating the documentation soon.

Just to respond to a couple things.  The PSCore console is PowerShell Core.  It's the cross-platform version of PowerShell.  It's embedded in Remotely, so it doesn't need to be installed on the endpoint.

PSCore, WinPS, CMD, and Bash can all be used to send commands to multiple endpoints simultaneously.

You can switch between command modes using "/".  For example, "/pscore".

You can use the shortcut Ctrl + Q to clear the contents of the output window.  It can get laggy if too much is in there.

You can select multiple devices by holding Ctrl while clicking on them.  Or, after you apply a filter or select a device group, "Select All" button will select only the visible devices.

**Comment by lucent-sea** [comment]
Please request at https://remotely.featureupvote.com/.  I can only work on one bug or feature at a time.   A voting system helps determine which features gets attention first.
