### ISSUE TITLE
Linux instant support client: requires libx11-dev, libgdiplus, libxtst-dev

### ISSUE THREAD

**Issue by Yvan-Masson** [lucent-sea/Remotely#91]
Hi,

On a fresh Ubuntu 18.04 with .Net Core runtime installed, the Linux instant support client (from https://app.remotely.one/Agents) does not work before installing the following packages:
- libx11-dev
- libgdiplus 
- libxtst-dev

As these packages are rarely installed, would it be possible to:
- indicate these dependencies to the README.md
- indicate how to build the client to include these dependencies

Thanks,
Yvan

**Comment by Jay-Rad** [comment]
Hello!

Thanks for bringing this to my attention.  I'll see about including them.

**Comment by lucent-sea** [comment]
I added documentation for this.  The app should show a warning if the dependencies are missing.

More research would be needed for including the dependencies directly, and if the licenses for each library would allow it.  Features can be suggested and upvoted here:  https://remotely.featureupvote.com/
