### ISSUE TITLE
Problem with unattended access sometimes doesn't respond at all.

### ISSUE THREAD

**Issue by McDouble2020** [lucent-sea/Remotely#92]
I've noticed on computers that are working just fine, unattended, sometimes they just don't respond at all the next day. I can confirm the command works from the command line:

C:\Program Files\Remotely\Remotely Agent (x64)\ScreenCast\Remotely_ScreenCast.exe -mode Unattended -requester obfuscated-id -serviceidobfuscated-id -deviceid obfuscated-id -host https://myhost.com

This works if I open cmd prompt and run it manually, which leads me to believe there's an issue somewhere with the code launching the program from the service.

Maybe it's not able to select the right user / desktop reference? 

This command returns TRUE:

var result = Win32Interop.OpenInteractiveProcess(rcBinaryPath + $" -mode Unattended -requester {requesterID} -serviceid {serviceID} -deviceid {ConnectionInfo.DeviceID} -host {ConnectionInfo.Host}", "default", true, out _);

But on the destination computer, Remotely_ScreenCast.exe either doesn't launch or it launches and closes immediately.

**Comment by McDouble2020** [comment]
When it fails, nothing is written to Remotely_Logs.log

If I recompile and replace it with a new Remotely_Screencast.exe it fixes the issue for a few days, until it breaks again.

**Comment by Jay-Rad** [comment]
Hmm.  I haven't experienced this myself.

When this happens, are you still able to issue PowerShell Core commands to the main agent?

And do you get the little toast message at the top, "Starting remote control.", when trying to start remote control?

If recompiling and replacing the ScreenCast EXE fixes it, it sounds like an antivirus might be blocking it.  The hash changes when it's recompiled, and it works for a bit.  Then the AV detects it again and blocks it.  Can you check your AV logs?
